```{r}
# FASTR - Chlorophyll and Ammonia Comparison
# purpose: qualitatively determine relationship b/w chla and NH3
# author: Sarah Perry
# contact: seperry83@gmail.com
```

```{r message=FALSE, warning=FALSE}
# import packages
library(ggplot2)
library(tidyverse)

# source functions
source('d-wq_chl-nh3_plots_funcs.R')
```

```{r message=FALSE}
# --- Import Data ---
# define main FASTR filepath (assumes sync'd with Sharepoint)
fp_fastr <- 'California Department of Water Resources/Office of Water Quality and Estuarine Ecology - North Delta Flow Action/'

# define relative filepaths 
fp_rel_wq <- paste(fp_fastr,'WQ_Subteam/Processed_Data/Discrete/Discrete_Output_Lab.csv', sep = '')
fp_rel_dates <- paste(fp_fastr,'Data Management/FlowDatesDesignations.csv', sep = '')

# define absolute filepaths
fp_abs_wq <- get_abs_path(fp_rel_wq)
fp_abs_dates <- get_abs_path(fp_rel_dates)

# read in data
df_wq <- read_csv(fp_abs_wq)
df_dates <- read_csv(fp_abs_dates)

# --- Clean Data ---
# convert NDs to NA 
df_wq$Result[df_wq$LabDetect == 'Non-detect'] <- NA

# subset df_wq
df_wq_long <- select(df_wq, c('StationCode','Region','DateTime','Result','Analyte'))

# create date/year columns (character type)
df_wq_long$Date <- format(strptime(df_wq_long$DateTime, '%m/%d/%Y'),'%m/%d/%Y')
df_wq_long$Year <- format(strptime(df_wq_long$DateTime, '%m/%d/%Y'),'%Y')

# add full analyte name column
# df_wq <- add_analyte_names(df_wq)

# add in phase actions (will also convert 'Date' column to date type)
df_wq_long <- add_phase_actions(df_wq_long, df_dates)

# convert to wide
df_wq_wide <- spread(df_wq_long, Analyte, Result)

# convert NH3 data to proper units
df_wq_wide$DisAmmonia_ugDl <- df_wq_wide$DisAmmonia * 100
df_wq_wide$DisAmmonia_umolL <- df_wq_wide$DisAmmonia_ugDl * 0.5872
```

```{r}
# source functions
source('d-wq_chl-nh3_plots_funcs.R')

# --- Prep for Graphs ---
# relevant variables
varis <- c('Region','Year')
width <- c(10, 10)
height <- c(12, 14)

# order ActionPhase column
df_wq_wide$ActionPhase <- factor(df_wq_wide$ActionPhase, levels = c('Pre', 'During', 'Post'))

# --- Create Plots --
for (i in seq(varis)) {
  # create plots
  p <- create_graph(df_wq_wide, vari)
  
  # save graphs
  fp_rel_save <- paste(fp_fastr,'WQ_Subteam/Raw_Plots/Discrete/Chla-NH3',sep = '')
  fp_abs_save <- get_abs_path(fp_rel_save)

  ggsave(
    paste(fp_abs_save,'/Chla-NH3_',varis[i],'.png',sep = ''),
    p,
    width = width[i],
    height = height[i],
    unit = 'in'
     )
}

```

```{r}
vari[i]
```
```{r}
seq(varis)
```

