```{r}
# FASTR D-WQ ANOVAs
# Author: Sarah Perry
# Date created: 01/27/2020
# Purpose: ANOVAS for D-WQ

# import packages and scripts
library(tidyverse)
library(lubridate)
library(ARTool)
source('global_ndfa_funcs.R')
```

```{r Import Data}
# define absolute filepaths
fp_abs_discrete <- ndfa_abs_sp_path('WQ_Subteam/Processed_Data/Discrete/WQ_INPUT_Discrete_Lab_2021-01-25.csv')
fp_abs_wy <- ndfa_abs_sp_path('WQ_Subteam/Processed_Data/Discrete/Analysis/FlowDatesDesignations_45days.csv')
fp_abs_region <- ndfa_abs_sp_path('WQ_Subteam/Processed_Data/Discrete/Analysis/NDFA_map.csv')

# read in data
df_discrete <- read_csv(fp_abs_discrete)
df_water_year <- read_csv(fp_abs_wy)
df_region <- read_csv(fp_abs_region)

# remove excess cols in df_region
df_region <- subset(df_region, select = c(Station, BroadRegion))

#remove sites we aren't including (not available for all years), create a column for year
remove <- c('DWT', 'SRH', 'SDI', 'SHR', 'SRV', 'WWT', 'RMB')
df_discrete <- filter(df_discrete, !StationCode %in% remove)

# standardize/rename Date col
df_discrete$DateTime <- as.Date(df_discrete$DateTime)
df_discrete <- rename(df_discrete, c('Date' = 'DateTime'))

# rename Station col
df_discrete <- rename(df_discrete, c('Station' = 'StationCode'))

# add flow action dates
df_discrete <- ndfa_action_periods(df_discrete, na_action_remove = TRUE, keep_action_dates = FALSE)

# add metadata cols
df_wq <- merge(df_discrete, df_water_year, by = c('Year')) 
df_wq <- merge(df_wq, df_region, by = c('Station')) 

# standardize names
df_wq$Result[df_wq$Result == '< MDL' | df_wq$Result == '< RL'] <- NA
df_wq$Result <- as.numeric(df_wq$Result)


# rm extra dfs
rm(df_water_year, df_region, df_discrete)

# list of analytes
analytes <- unique(df_wq$Analyte)

# average over stations/year
#df_wq <- df_wq %>%
#  group_by(Station, FlowPulseType, FlowActionPeriod, BroadRegion, Year, Analyte) %>%
#  summarize(Result = mean(Result, na.rm = TRUE)) %>%
#  ungroup()
```

```{r ANOVA - set to RL}
for (analyte in analytes){
  df_sub <- df_wq %>% filter(Analyte == 'Chla')
  
  df_sub$Result <- with(df_sub, ifelse(is.na(Result), RL, Result))

  aov_res <- aov(log(Result) ~ FlowPulseType*FlowActionPeriod + BroadRegion*FlowActionPeriod + BroadRegion*FlowPulseType + Error(Station), df_sub)
  
  # # residuals histogram
  # print(hist(aov_res$residuals, main = analyte))
  # 
  # # fitted vs. residuals
  # print(plot(aov_res, which = 1, main = analyte))
  # 
  # # q-q plot
  # print(plot(aov_res, which = 2, main = analyte))
  # 
  # # scale-location
  # print(plot(aov_res, which = 3, main = analyte))
  # 
  # # residuals vs leverage
  # print(plot(aov_res, which = 5, main = analyte))
  
  print(paste0('~*~*~*~',analyte,'~*~*~*~'))
  print(summary(aov_res))
  break
}
```

Look for unequal sample sizes.
FlowPulseType -- are all stations included? dif number of stations per region?

Take a mean of the values (of the station over a flow pulse period).

```{r ANOVA - set to ~0}
for (analyte in analytes){
  df_sub <- df_wq %>% filter(Analyte == 'Chla')
  
  df_sub$Result[is.na(df_sub$Result)] <- 0.01

  df_wq_sub$Year2 = as.factor(df_wq_sub$Year)
  
  aov_res <- aov(log(Result) ~ Year2*FlowActionPeriod + BroadRegion*FlowActionPeriod + BroadRegion*Year2, df_wq_sub)
  summary(aov_res)

  
    aov_res2 <- aov(log(Result) ~ FlowPulseType*FlowActionPeriod + BroadRegion*FlowActionPeriod + BroadRegion*FlowPulseType, df_wq_sub)
  summary(aov_res2)
  
  library(rstatix)
  aov_res2 <- aov(log(Result) ~ Year*FlowActionPeriod + BroadRegion*FlowActionPeriod + BroadRegion*FlowPulseType + Error(Station), df_sub)
  summary(aov_res2)
  
  aov_res3 = anova_test(df_sub, dv =Result, between = c(Year, FlowActionPeriod, BroadRegion), wid = Station, type = 3)
  aov_res3
  
    lm_res <- lmer(log(Result) ~ FlowPulseType*FlowActionPeriod + BroadRegion*FlowActionPeriod + BroadRegion*FlowPulseType + (1|Station), df_wq)
  
  summary(lm_res)
    # # residuals histogram
  # print(hist(aov_res$residuals, main = analyte))
  # 
  # # fitted vs. residuals
  # print(plot(aov_res, which = 1, main = analyte))
  # 
  # # q-q plot
  # print(plot(aov_res, which = 2, main = analyte))
  # 
  # # scale-location
  # print(plot(aov_res, which = 3, main = analyte))
  # 
  # # residuals vs leverage
  # print(plot(aov_res, which = 5, main = analyte))
  
  print(paste0('~*~*~*~',analyte,'~*~*~*~'))
  print(summary(aov_res))
  break
}
```

```{r ANOVA - random sub 1}
for (analyte in analytes){
  df_sub <- df_wq %>% filter(Analyte == 'Chla')

  for (i in seq(length(df_sub$Station))){
    if (is.na(df_sub$Result[i])){
      vec <- seq(0.01, df_sub$RL[i], by = 0.01)
      df_sub$Result[i] <- sample(vec, size = 1)    
    }
  }

  aov_res <- aov(log(Result) ~ FlowPulseType*FlowActionPeriod + BroadRegion*FlowActionPeriod + BroadRegion*FlowPulseType + Error(Station), df_sub)
  
  # # residuals histogram
  # print(hist(aov_res$residuals, main = analyte))
  # 
  # # fitted vs. residuals
  # print(plot(aov_res, which = 1, main = analyte))
  # 
  # # q-q plot
  # print(plot(aov_res, which = 2, main = analyte))
  # 
  # # scale-location
  # print(plot(aov_res, which = 3, main = analyte))
  # 
  # # residuals vs leverage
  # print(plot(aov_res, which = 5, main = analyte))
  
  print(paste0('~*~*~*~',analyte,'~*~*~*~'))
  print(summary(aov_res))
  break
}
```

```{r ANOVA - random sub 2}
for (analyte in analytes){
  df_sub <- df_wq %>% filter(Analyte == 'Chla')

  for (i in seq(length(df_sub$Station))){
    if (is.na(df_sub$Result[i])){
      vec <- seq(0.01, df_sub$RL[i], by = 0.01)
      df_sub$Result[i] <- sample(vec, size = 1)    
    }
  }

  aov_res <- aov(log(Result) ~ FlowPulseType*FlowActionPeriod + BroadRegion*FlowActionPeriod + BroadRegion*FlowPulseType + Error(Station), df_sub)
  
  # # residuals histogram
  # print(hist(aov_res$residuals, main = analyte))
  # 
  # # fitted vs. residuals
  # print(plot(aov_res, which = 1, main = analyte))
  # 
  # # q-q plot
  # print(plot(aov_res, which = 2, main = analyte))
  # 
  # # scale-location
  # print(plot(aov_res, which = 3, main = analyte))
  # 
  # # residuals vs leverage
  # print(plot(aov_res, which = 5, main = analyte))
  
  print(paste0('~*~*~*~',analyte,'~*~*~*~'))
  print(summary(aov_res))
  break
}
```

```{r ANOVA - random sub 3}
for (analyte in analytes){
  df_sub <- df_wq %>% filter(Analyte == 'Chla')

  for (i in seq(length(df_sub$Station))){
    if (is.na(df_sub$Result[i])){
      vec <- seq(0.01, df_sub$RL[i], by = 0.01)
      df_sub$Result[i] <- sample(vec, size = 1)    
    }
  }

  aov_res <- aov(log(Result) ~ FlowPulseType*FlowActionPeriod + BroadRegion*FlowActionPeriod + BroadRegion*FlowPulseType + Error(Station), df_sub)

  # # residuals histogram
  # print(hist(aov_res$residuals, main = analyte))
  # 
  # # fitted vs. residuals
  # print(plot(aov_res, which = 1, main = analyte))
  # 
  # # q-q plot
  # print(plot(aov_res, which = 2, main = analyte))
  # 
  # # scale-location
  # print(plot(aov_res, which = 3, main = analyte))
  # 
  # # residuals vs leverage
  # print(plot(aov_res, which = 5, main = analyte))
  
  print(paste0('~*~*~*~',analyte,'~*~*~*~'))
  print(summary(aov_res))
  break
}
```