---
title: "FISH_MAN_InitialExploration"
author: "Catarina Pien"
date: "2/24/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warnings = FALSE)

library(tidyverse)
library(lubridate)

```

## Download data

```{r download and filter dates}
Fish_all <- read.csv("fish data/FISH_MAN_allIEPsurveys_20200521.csv")
FlowDesignation <- read.csv("fish data/FlowDatesDesignations.csv")

# Define date, create month
Fish_all$Date <- ymd(Fish_all$Date)
Fish_all$Month <- month(Fish_all$Date)
Fish_all$Day <- day(Fish_all$Date)
Fish_all$Year <- ordered(Fish_all$Year)
FlowDesignation$Year <- ordered(FlowDesignation$Year)
FlowDesignation$PreFlowStart <- mdy(FlowDesignation$PreFlowStart)
FlowDesignation$PreFlowEnd <- mdy(FlowDesignation$PreFlowEnd)
FlowDesignation$PostFlowStart <- mdy(FlowDesignation$PostFlowStart)
FlowDesignation$PostFlowEnd <- mdy(FlowDesignation$PostFlowEnd)

# Look at datasets
DBsum <- Fish_all %>% 
  group_by(Survey, Year, Month) %>% summarize(n())
head(DBsum)

# Merge data from FlowDesignation Table (Water Year Type, Flow days and type)
# Filter only Pre-During-Post Flow Action Data. 
# We have a during action, and then Pre = 30 days before/Post = 30 days after
Fish_ndfa <- inner_join(Fish_all,FlowDesignation, by = "Year")
Fish_ndfa <- Fish_ndfa %>%
   mutate(ActionPhase = ifelse(Date > PreFlowStart & Date<PreFlowEnd, "Pre", NA)) %>%
   mutate(ActionPhase = replace(ActionPhase, Date > PreFlowEnd & Date < PostFlowStart, "During")) %>% 
   mutate(ActionPhase = replace(ActionPhase, Date > PostFlowStart & Date < PostFlowEnd, "Post")) %>%
    filter(!is.na(ActionPhase)) %>%
   select(-c(PreFlowStart:PostFlowEnd)) %>%
   arrange(Date, Survey, StationCode, CommonName)

# Order Action Phases
Fish_ndfa$ActionPhase <- as.factor(Fish_ndfa$ActionPhase)
Fish_ndfa$ActionPhase <-  factor(Fish_ndfa$ActionPhase, levels(Fish_ndfa$ActionPhase)[c(3,1,2)])
```

## Datasets by fish types
```{r species composition, echo=FALSE}

list_native <- c("Sacramento Pikeminnow", "Splittail", "Hitch", "Fathead Minnow",
                           "Golden Shiner", "Hardhead", "Sacramento Sucker", "Sacramento Blackfish")
list_smeltish <- c("Wakasagi", "Inland Silverside")
list_smeltpred <- c("Largemouth Bass", "Smallmouth Bass", "Striped Bass", "Spotted Bass")
list_cyprinid <- c("Sacramento Pikeminnow", "Sacramento Splittail", "Hitch", "Fathead Minnow",
                           "Golden Shiner", "Hardhead", "Carp", "Goldfish")
list_pelagic <- c("Threadfin Shad", "American Shad", "Striped Bass")
```

### Make it easier to plot

```{r plot fcns}
## Plotting functions

# Plot overall abundance
plotabund <- function(df) {
  a <-  ggplot(data = df, aes(x = CommonName, y = n, fill = Year)) + geom_col() + 
  theme_bw() + theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 14),
                       axis.title = element_text(size = 14),
                       strip.text.x = element_text(size = 14),
                     legend.text = element_text(size = 14)) 
  return(a) }

# Plot CPUE by Species
plotCPUE <- function(df) {
  a <-  ggplot(data = df, aes(x = CommonName, y = CPUE, fill = Year)) + geom_col() + 
    theme_bw() + theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 14),
                       axis.title = element_text(size = 14),
                       strip.text.x = element_text(size = 14),
                       legend.text = element_text(size = 14)) 
  return(a) }

# Plot CPUE by Phase
plotCPUEPhaseYear <- function(df) {
  a <-  ggplot(data = df, aes(x = ActionPhase, y = CPUE, fill = CommonName)) + geom_col() +
    facet_wrap(~Year) +
    theme_bw() + theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 14),
                       axis.title = element_text(size = 14),
                       strip.text.x = element_text(size = 14),
                       legend.text = element_text(size = 14)) 
  return(a) }

# Plot mean CPUE
plotmeanCPUEPhaseYr <- function(df) {
  a <-  ggplot(data = df, aes(x = ActionPhase, y = mean.CPUE, fill = CommonName)) + geom_col() +
    facet_wrap(~Year) + theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 14),
        axis.title = element_text(size = 14),
        strip.text.x = element_text(size = 14),
        legend.text = element_text(size = 14)) 
  return(a) }
```

## Make plots
```{r exploratory plots, fig.width = 10}

## All surveys
spcomp <- Fish_ndfa %>%
  group_by(Year, Survey, CommonName) %>%
  summarize(n = n()) %>%
  arrange(n)

ggplot(spcomp, aes(x = Year, y = n, fill = CommonName)) + 
  geom_col() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

## Filter datasets
Yolo <- spcomp %>% filter(Survey == "Yolo")
DJFMP <- spcomp %>% filter(Survey == "DJFMP")
EDSM <- spcomp %>% filter(Survey == "EDSM")
FMWT <- spcomp %>% filter(Survey == "FMWT")
Townet <- spcomp %>% filter(Survey == "Townet")

# dffilter <- function(df, SurveyName) {
#   quo_SurveyName = enquo(SurveyName)
#   print(quo_SurveyName)
#   
#   newdf <- df %>%
#     dplyr::filter(Survey == SurveyName) 
#   return(newdf)
# }

# Make plots!
plotabund(Yolo)
plotabund(FMWT)
plotabund(EDSM)
plotabund(DJFMP)
plotabund(Townet)

# Common Species: 
# DJFMP: ISS, LMG, Sac Pikeminnow, Sucker, Shimofuri Goby, STB, AMS, TFS, Mosquito, YF Goby, Logperch
# EDSM: TFS, Wakasagi, ISS, American Shad
# FMWT: American Shad, TFS, Striped Bass, Wakasagi, White Catfish, Inland Silverside, Delta Smelt
# Yolo: ISS, Black Crappie, Bluegill, AMS, LMB, STB, TFS, Mosquitofish, White Catfish, White Crappie, Common Carp 
# Townet: TFS, AMS, ISS, Shimofuri, STB, Tridentiger, White Catfish

```

## Work with seine data
```{r seine}

### Filter out seine method
Seine <-  Fish_ndfa %>%
  filter(MethodCode == "SEIN" | MethodCode == "BSEIN") 

### Complete Cases
# For each Date, Survey, StationCode combination, make sure each fish species is represented with 
# either positive count or zero. 
Seine_completecase <- Seine %>%
  group_by(Date, Survey, StationCode, CommonName) %>%
  summarize(sum.count = sum(totalCount)) %>%
  ungroup() %>%
  complete(CommonName, nesting(Date, Survey, StationCode), fill = list(sum.count = 0)) %>%
  arrange(Date,Survey, StationCode,CommonName)

### Merge back together with rest of data

# Get distinct samples
Seine_samples <- Seine %>% select(-c(CommonName, totalCount)) %>% distinct()

# Merge 
Seine_complete <- left_join(Seine_completecase, Seine_samples, by = c("Date", "Survey", "StationCode"))
# There is a Yolo sample with two volumes... this is why there are more rows of Seine_complete

### Calculate CPUE
Seine_CPUE <- Seine_complete %>%
  mutate(CPUE = sum.count/VolumeSampled)

### Rearrange columns 
Seine_f <- Seine_CPUE[, c("Date", "Year", "Month", "Day", "Survey", "StationCode", 
                          "Latitude", "Longitude","MethodCode",
                         "WYType", "FlowPulseType", "NetFlowDays","ActionPhase", 
                         "Secchi", "Conductivity", "WaterTemp", "Tow",
                         "Depth", "VolumeSampled",  "CommonName", "sum.count", "CPUE")]

### Mean CPUE 
## Calculate means for each species by year-location-actionphase
CPUE_means_seine_phase <- Seine_f %>%
  group_by(Year, Survey, StationCode, ActionPhase, CommonName) %>% 
  summarize(mean.CPUE = mean(CPUE)) 

```

### Seine - native species
```{r seine plots, fig.width = 10}
##### Native Species

### Filter datasets
## Total CPUE
Seine_natives <- Seine_f %>% filter(CommonName %in% list_native) %>% filter(Year>2011)
Seine_natives_Yolo <- Seine_natives %>% filter(Survey == "Yolo")
Seine_natives_DJFMP <- Seine_natives %>% filter(Survey == "DJFMP")
Seine_Pikeminnow <- Seine_natives %>% filter(CommonName == "Sacramento Pikeminnow")
Seine_Splittail <- Seine_natives %>% filter(CommonName == "Splittail")
## MeanCPUE
CPUE_sn_natives <- CPUE_means_seine_phase %>% filter(CommonName %in% list_native)
CPUE_sn_Pike <- CPUE_means_seine_phase %>% filter(CommonName == "Sacramento Pikeminnow")
CPUE_sn_Split <- CPUE_means_seine_phase %>% filter(CommonName == "Splittail")

### Plot! 
## Total CPUE
plotCPUE(Seine_natives)
plotCPUEPhaseYear(Seine_natives)
plotCPUEPhaseYear(Seine_natives_Yolo)
plotCPUEPhaseYear(Seine_natives_DJFMP)
plotCPUEPhaseYear(Seine_Pikeminnow)
plotCPUEPhaseYear(Seine_Splittail)

## Average CPUE
plotmeanCPUEPhaseYr(CPUE_sn_natives)
plotmeanCPUEPhaseYr(CPUE_sn_Pike)
plotmeanCPUEPhaseYr(CPUE_sn_Split)

ggplot(CPUE_sn_natives, aes(x = ActionPhase, y = mean.CPUE, fill = Year, group = Year)) +
  geom_col(position = "dodge2")

```

### Seine - smeltish
```{r smeltish plots, fig.width = 10}
# Wakasagi and Silversides
## Total CPUE
Seine_smeltish <- Seine_f %>% filter(CommonName %in% list_smeltish)
Seine_smeltish_Yolo <- Seine_smeltish %>% filter(Survey == "Yolo")
Seine_smeltish_DJFMP <- Seine_smeltish %>% filter(Survey == "DJFMP")

## Mean CPUE
CPUE_sn_smeltish <- CPUE_means_seine_phase %>% filter(CommonName %in% list_smeltish)
CPUE_sn_ISS <- CPUE_means_seine_phase %>% filter(CommonName == "Inland Silverside")

### Plots

## Total CPUE
plotCPUEPhaseYear(Seine_smeltish)
plotCPUEPhaseYear(Seine_smeltish_Yolo)
plotCPUEPhaseYear(Seine_smeltish_DJFMP)

## Mean CPUE
plotmeanCPUEPhaseYr(CPUE_sn_smeltish)
plotmeanCPUEPhaseYr(CPUE_sn_ISS)
```

### Tow data
* Use Townet, EDSM, FMWT

```{r tow data}
Tows <- Fish_ndfa %>% filter(Survey %in% c("EDSM", "Townet", "FMWT"))

### Complete Cases
# For each Date, Survey, StationCode combination, make sure each fish species is represented with 
# either positive count or zero. 
Tow_completecase <- Tows %>%
  group_by(Date, Survey, StationCode, Tow, CommonName) %>%
  summarize(sum.count = sum(totalCount)) %>%
  ungroup() %>%
  complete(CommonName, nesting(Date, Survey, StationCode, Tow), fill = list(sum.count = 0)) %>%
  arrange(Date,Survey, StationCode,CommonName)

### Merge back together with rest of data

# Get distinct samples
Tow_samples <- Tows %>% select(-c(CommonName, totalCount)) %>% distinct()

# Merge 
Tow_complete <- left_join(Tow_completecase, Tow_samples, by = c("Date", "Survey", "StationCode", "Tow"))

### Calculate CPUE
Tow_CPUE <- Tow_complete %>%
  mutate(CPUE = sum.count/VolumeSampled)

### Rearrange columns 
Tow_f <- Tow_CPUE[, c("Date", "Year", "Month", "Day", "Survey", "StationCode",   
                          "Latitude", "Longitude","MethodCode",
                         "WYType", "FlowPulseType", "NetFlowDays","ActionPhase", 
                         "Secchi", "Conductivity", "WaterTemp", "Tow",
                         "Depth", "VolumeSampled",  "CommonName", "sum.count", "CPUE")]

### Mean CPUE 
## Calculate means for each species by year-location-actionphase
CPUE_means_tow_phase <- Tow_f %>%
  group_by(Year, Survey, StationCode, Tow, ActionPhase, CommonName) %>% 
  summarize(mean.CPUE = mean(CPUE)) 


```

### Tow - smeltish
```{r tow wag and silverside, fig.width = 10}
# Wakasagi and Silversides
## Total CPUE
Tow_smeltish <- Tow_f %>% filter(CommonName %in% list_smeltish)
Tow_smeltish_EDSM <- Tow_smeltish %>% filter(Survey == "EDSM")
Tow_smeltish_Townet <- Tow_smeltish %>% filter(Survey == "Townet")
Tow_smeltish_FMWT <- Tow_smeltish %>% filter(Survey == "FMWT")
Tow_wag <- Tow_smeltish %>% filter(CommonName == "Wakasagi")

## Mean CPUE
CPUE_tow_smeltish <- CPUE_means_tow_phase %>% filter(CommonName %in% list_smeltish)
CPUE_tow_WAG <- CPUE_means_tow_phase %>% filter(CommonName == "Wakasagi")

### Plots

## Total CPUE
plotCPUEPhaseYear(Tow_smeltish)
plotCPUEPhaseYear(Tow_smeltish_EDSM)
plotCPUEPhaseYear(Tow_smeltish_Townet)
plotCPUEPhaseYear(Tow_smeltish_FMWT)
plotCPUEPhaseYear(Tow_wag)

## Mean CPUE
plotmeanCPUEPhaseYr(CPUE_sn_smeltish)
plotmeanCPUEPhaseYr(CPUE_tow_WAG)
```

# Pelagic species 

```{r pelagic, fig.width = 10}

# TFS, AMS, Striped Bass
## Total CPUE
pelagic_t <- Tow_f %>% filter(CommonName %in% list_pelagic)
pelagic_s <- Seine_f%>% filter(CommonName %in% list_pelagic)

Tow_pelagic_EDSM <- pelagic_t %>% filter(Survey == "EDSM")
Tow_pelagic_Townet <- pelagic_t %>% filter(Survey == "Townet")
Tow_pelagic_FMWT <- pelagic_t %>% filter(Survey == "FMWT")
Seine_pelagic_Yolo <- pelagic_s %>%filter(Survey == "Yolo")
Seine_pelagic_DJFMP <- pelagic_s %>%filter(Survey == "DJFMP")
Tow_stb <- pelagic_t %>% filter(CommonName == "Striped Bass")
Seine_stb <- pelagic_s %>% filter(CommonName == "Striped Bass")
STB <- rbind(Tow_stb, Seine_stb) # combine tow and seine

## Mean CPUE
CPUE_tow_pelagic <- CPUE_means_tow_phase %>% filter(CommonName %in% list_pelagic)
CPUE_tow_STB <- CPUE_means_tow_phase %>% filter(CommonName == "Striped Bass")

### Plots

## Total CPUE
plotCPUEPhaseYear(pelagic_t)
plotCPUEPhaseYear(pelagic_s)
plotCPUEPhaseYear(Tow_pelagic_EDSM)
plotCPUEPhaseYear(Tow_pelagic_Townet)
plotCPUEPhaseYear(Tow_pelagic_FMWT)
plotCPUEPhaseYear(Seine_pelagic_Yolo)
plotCPUEPhaseYear(Seine_pelagic_DJFMP)
plotCPUEPhaseYear(STB) 

## Mean CPUE
plotmeanCPUEPhaseYr(CPUE_tow_pelagic)
plotmeanCPUEPhaseYr(CPUE_tow_STB)
```
