---
title: "zoop_LIS_flow_models"
author: "Laura"
date: "2026-02-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Global code and functions

```{r load packages and functions, message = FALSE, warning = FALSE}
# Load packages
library(tidyverse)
library(scales)
library(mgcv)
library(ggeffects)
library(emmeans)
library(multcomp)
library(gratia)
library(patchwork)
library(here)
library(conflicted)

# Declare package conflict preferences 
conflicts_prefer(dplyr::filter(), dplyr::lag(), dplyr::select())
```

Display current versions of R and packages used for this analysis:

```{r print session info}
devtools::session_info()
```


```{r functions and global code}
# Calculate effects of flow on zooplankton for each year holding the
  # non-focal variables constant - marginal effects/adjusted predictions
calc_flow_yr_marg_eff <- function(df_data, m_gam) {
  # Calculate min and max flows for each year to narrow down x-axis in the
    # effects plots
  df_flow_yr_summ <- df_data %>% 
    summarize(
      Flow_min = min(Flow),
      Flow_max = max(Flow),
      .by = c(Year_fct)
    ) %>% 
    mutate(
      Flow_buffer = (Flow_max - Flow_min) * 0.05,
      Flow_min = Flow_min - Flow_buffer,
      Flow_max = Flow_max + Flow_buffer
    ) %>% 
    select(-Flow_buffer)
  
  # Calculate marginal effects
  as.data.frame(
    predict_response(m_gam, terms = c("Flow", "Year_fct"), margin = "marginalmeans"),
    terms_to_colnames = TRUE
  ) %>% 
  as_tibble() %>% 
  # Narrow down range of flow values for each station
  left_join(df_flow_yr_summ, by = join_by(Year_fct)) %>% 
  filter(Flow >= Flow_min & Flow <= Flow_max)
}

# Create effects plot of flow on zooplankton by year
plot_eff_flow_by_yr <- function(df_eff, df_data) {
  df_eff %>% 
    ggplot(aes(x = Flow, y = predicted)) +
    geom_point(data = df_data, aes(y = zoop_log), alpha = 0.6) +
    geom_line(linewidth = 1) +
    geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = 0.25) +
    facet_wrap(vars(Year_fct), scales = "free_x", nrow = 1) +
    theme_bw() +
    labs(
      title = df_data$StationCode[1],
      x = "Flow (cfs)",
      y = "log(Zooplankton abundance)"
    ) +
    scale_x_continuous(labels = label_comma(), breaks = breaks_extended()) +
    theme(
      axis.text = element_text(size = 8),
      axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)
    )
}

# Create boxplots of zooplankton by year showing Tukey post-hoc results
boxplot_cont_yr <- function(em_obj, df_data, xlab = TRUE) {
  # Create table of contrasts and convert it to a tibble for plot
  df_yr_cont <- em_obj %>% 
    cld(sort = FALSE, Letters = letters) %>% 
    as_tibble() %>% 
    mutate(
      group = str_remove_all(.group, fixed(" ")),
    ) %>% 
    # Add min and max values of observed data to the Tukey post-hoc results and
      # calculate vertical positioning of letters
    left_join(
      df_data %>% 
        summarize(
          max_val = max(zoop_log),
          min_val = min(zoop_log),
          .by = Year_fct
      ), 
      by = join_by(Year_fct)
    ) %>% 
    mutate(
      max_val = if_else(upper.CL > max_val, upper.CL, max_val),
      y_pos = max_val + (max_val - min_val) / 10,
      # Make all post-hoc contrast letters at same height equal to max of all
      y_pos = max(y_pos)
    ) %>% 
    select(
      Year_fct,
      emmean,
      lower.CL,
      upper.CL,
      group,
      y_pos
    )
  
  # Create boxplot showing Tukey post-hoc results
  df_yr_cont %>% 
    ggplot(
      aes(
        x = Year_fct,
        y = emmean,
        ymin = lower.CL,
        ymax = upper.CL
      )
    ) +
    geom_boxplot(
      data = df_data,
      aes(x = Year_fct, y = zoop_log),
      inherit.aes = FALSE
    ) +
    geom_crossbar(
      color = "grey82", 
      fill = "grey", 
      alpha = 0.7, 
      linewidth = 0.1
    ) +
    geom_point(color = "red") +
    geom_text(aes(y = y_pos, label = group), size = 3) +
    labs(
      title = df_data$StationCode[1],
      x = "Year",
      y = "log(Zooplankton abundance)"
    ) +
    theme_bw() +
    theme(axis.text = element_text(size = 8))
}

# Create smooth of Week plot
plot_smooth_week <- function(m_gam, station) {
  ls_plt <- draw(m_gam, residuals = TRUE, rug = FALSE, wrap = FALSE)
  
  # Extract plot from list and format
  chuck(ls_plt, 1) + 
    theme_bw() + 
    labs(title = station, caption = NULL)
}
```

# Import Data

```{r import data}

# Import zooplankton data
df_zoop <- read_csv(here("Zoop_code/Jesse-zoop-analyses/zoopNDFA7.csv"))

# Import weekly average flow data
df_flow <- readRDS(here("manuscript_synthesis/data/processed/flow_week_avg_2013-2019.rds"))
```

# Prepare Data

```{r prepare zoop data}
#add week of year to zoop data
df_zoop_weekly<-df_zoop%>%mutate(Week=week(Date))

# Create a vector for the factor order of StationCode
sta_order <- c("RD22", "STTD", "LIB", "RVB")

#create list of flow stations that we will use in analysis
flow_stations<-c("LIS", "RD22")

# We will use LIS flow data as a proxy for STTD, LIB, and RVB
df_flow_c <- df_flow %>% filter(StationCode%in%flow_stations)
df_zoop_stations<-c("STTD", "LIB", "RVB") #define statiosn for which we want to use LIS flow data


# Prepare zooplankton and flow data for analysis
df_zoop2 <- df_zoop_weekly %>% 
  select(StationCode, Year, Week, cpue) %>% 
  drop_na(cpue) %>% 
  # Filter to only include representative stations for 4 habitat types (RD22,
    # STTD, LIB, RVB) and only include years 2014-2019
  filter(
    StationCode %in% sta_order,
    Year %in% 2014:2019
  ) %>% 
  # Join flow data to zoop data
  left_join(df_flow_c, by = join_by(Year, Week))%>%
  #remove rows with RD22 as flow and STTD, LIB, or RVB as zoop
  filter(!(StationCode.x %in% df_zoop_stations & StationCode.y == "RD22")) %>%
  #remove rows with LIS as flow and RD22 as zoop
  filter(!(StationCode.x == "RD22" & StationCode.y == "LIS")) %>% 
  # Remove all NA flow values
  drop_na(Flow) %>% 
  mutate(
    # Scale and log transform chlorophyll values
    zoop_log = log(cpue),
    # Add a column for Year as a factor for the models
    Year_fct = factor(Year)
  ) %>% 
  arrange(StationCode.x, Year, Week) %>% 
  split(~ StationCode.x)

# Combine all data sets into a nested data frame to be used for analysis
ndfa_zoop <- 
  tibble(
    StationCode = sta_order,
    df_data = list(df_zoop2$RD22, df_zoop2$STTD, df_zoop2$LIB, df_zoop2$RVB)
  ) %>% 
  # Apply factor order to StationCode
  mutate(StationCode = factor(StationCode, levels = sta_order)) %>% 
  arrange(StationCode)
```

# Create GAMs

```{r create gams, warning = FALSE}
# Define base model formula
f_base <- " zoop_log ~ Year_fct * Flow + s(Week, bs = 'cc', k = 5)"



# Create gam models for each station
ndf_gam <- ndfa_zoop %>% mutate(
    str_formula = case_when(
      StationCode == "LIB" ~ paste(f_base),
      StationCode == "RVB" ~ paste(f_base),
      TRUE ~ f_base
    ),
    model = map2(
      str_formula,
      df_data,
      \(x, y) gam(
        formula = as.formula(x),
        data = y,
        method = "REML", 
        knots = list(week = c(0, 52))
      )
    )
  )
```

# Model Results

## ANOVA Tables

```{r gam anova tables, warning = FALSE}
# Create ANOVA tables for each GAM model and extract elements for export
ndf_gam_anova <- ndf_gam %>% 
  mutate(
    an_gam = map(model, anova),
    # Parametric terms
    df_parametric = map(
      an_gam, 
      \(x) as_tibble(chuck(x, "pTerms.table"), rownames = "Term")
    ),
    # Smooth terms
    df_smooth = map(
      an_gam, 
      \(x) as_tibble(chuck(x, "s.table"), rownames = "Term") %>% 
        rename(df = edf) %>% 
        select(-Ref.df)
    ),
    df_anova_tbl = map2(df_parametric, df_smooth, bind_rows)
  )

# Combine ANOVA tables and format for export
df_gam_anova_tbl_c <- ndf_gam_anova %>% 
  select(StationCode, df_anova_tbl) %>% 
  unnest(df_anova_tbl) %>% 
  transmute(
    Station = StationCode,
    Term,
    across(
      c("df", "F"),
      \(x) if_else(
        abs(x) < 0.01,
        formatC(signif(x, 3), digits = 2, format = "e"),
        formatC(signif(x, 3), digits = 3, format = "fg", flag = "#")
      )
    ),
    p_value = if_else(
      `p-value` < 0.001, 
      "< 0.001", 
      formatC(`p-value`, digits = 3, format = "f")
    )
  )

df_gam_anova_tbl_c
```
## Effect of Flow by Year

### Effect Plots

```{r gam flow year effect plots, warning = FALSE, fig.height = 9}
# Create effects plot of flow on zooplankton by year for each station
ndf_gam_eff_flow_plt <- ndf_gam %>% 
  mutate(
    df_marg_eff = map2(df_data, model, calc_flow_yr_marg_eff),
    plt_marg_eff = map2(df_marg_eff, df_data, plot_eff_flow_by_yr)
  )

# Combine effects plots together using patchwork
plt_gam_eff_flow <- 
  wrap_plots(ndf_gam_eff_flow_plt$plt_marg_eff, ncol = 1) + 
  plot_layout(axes = "collect")

plt_gam_eff_flow
```
### Slopes and p-values

```{r gam flow year effect stats}
# Calculate slopes and p-values of the modeled effects of flow on zoop by
  # year for each station
ndf_gam_eff_flow_stat <- ndf_gam %>% 
  mutate(
    em_gam_flow = map(model, \(x) emtrends(x, ~ Year_fct, var = "Flow")),
    df_stat = map(em_gam_flow, \(x) as_tibble(test(x)))
  )

# Combine slopes and p-values into one data frame for export
df_gam_eff_flow_stat <- ndf_gam_eff_flow_stat %>% 
  select(StationCode, df_stat) %>% 
  unnest(df_stat) %>% 
  # Format for export
  rename(
    Station = StationCode,
    Year = Year_fct,
    Flow_slope = Flow.trend,
    t_ratio = t.ratio,
    p_value = p.value
  ) %>% 
  mutate(
    p_value = if_else(
      p_value < 0.001, 
      "< 0.001", 
      formatC(p_value, digits = 3, format = "f")
    ),
    across(
      where(is.numeric),
      \(x) if_else(
        abs(x) < 0.01,
        formatC(signif(x, 3), digits = 2, format = "e"),
        formatC(signif(x, 3), digits = 3, format = "fg", flag = "#")
      )
    )
  )

df_gam_eff_flow_stat
```
## Year Contrasts

### Boxplots

```{r gam year contrast boxplots, warning = FALSE}
# Calculate estimated marginal means of year for each station
ndf_gam_cont_yr <- ndf_gam %>% 
  mutate(em_gam_yr = map(model, \(x) emmeans(x, ~ Year_fct)))

# Create boxplots showing Tukey post-hoc results of year contrasts for each station
ndf_gam_cont_yr_plt <- ndf_gam_cont_yr %>% 
  mutate(plt_cont_yr = map2(em_gam_yr, df_data, boxplot_cont_yr))

# Combine boxplots together using patchwork
plt_gam_cont_yr <- 
  wrap_plots(ndf_gam_cont_yr_plt$plt_cont_yr, ncol = 2) + 
  plot_layout(axes = "collect")

plt_gam_cont_yr
```
### Statistics

```{r gam year contrast stats}
# Generate pairwise Tukey post-hoc year contrasts for each station
ndf_gam_cont_yr_stat <- ndf_gam_cont_yr %>% 
  mutate(df_stat = map(em_gam_yr, \(x) as_tibble(pairs(x))))

# Combine pairwise Tukey post-hoc year contrasts into one data frame for export
df_gam_cont_yr_stat <- ndf_gam_cont_yr_stat %>% 
  select(StationCode, df_stat) %>% 
  unnest(df_stat) %>% 
  # Format for export
  rename(
    Station = StationCode,
    Contrast = contrast,
    Estimate = estimate,
    t_ratio = t.ratio,
    p_value = p.value
  ) %>% 
  mutate(
    p_value = if_else(
      p_value < 0.001, 
      "< 0.001", 
      formatC(p_value, digits = 3, format = "f")
    ),
    across(
      where(is.numeric),
      \(x) if_else(
        abs(x) < 0.01,
        formatC(signif(x, 3), digits = 2, format = "e"),
        formatC(signif(x, 3), digits = 3, format = "fg", flag = "#")
      )
    )
  )

print(df_gam_cont_yr_stat, n = Inf)
```
## s(Week) Plots

```{r gam sWeek plots, warning = FALSE}
# Create smooth of Week plots for each station
ndf_gam_s_week_plt <- ndf_gam %>% 
  mutate(plt_s_week = map2(model, StationCode, plot_smooth_week))

# Combine smooth of Week plots together using patchwork
plt_gam_s_week <- 
  wrap_plots(ndf_gam_s_week_plt$plt_s_week, ncol = 2) + 
  plot_layout(axis_titles = "collect") +
  plot_annotation(caption = "Basis: Cyclic CRS")

plt_gam_s_week
```
# Export Results

```{r export results}
# Define file path for figures and tables for the manuscript
fp_figures <- here("manuscript_synthesis/results/figures")
fp_tables <- here("manuscript_synthesis/results/tables")

# Export effects plot of flow by year for each station
ggsave(
  file.path(fp_figures, "zoop_LIS_flow_eff_plot_by_year_each_sta.jpg"),
  plot = plt_gam_eff_flow,
  width = 7,
  height = 9,
  units = "in"
)

ggsave(
  file.path(fp_figures, "zoop_LIS_flow_eff_plot_by_year_each_sta.pdf"),
  plot = plt_gam_eff_flow,
  width = 7,
  height = 9,
  units = "in"
)

# Export boxplots of year contrasts for each station
ggsave(
  file.path(fp_figures, "zoop_LIS_flow_year_contrasts_each_sta.jpg"),
  plot = plt_gam_cont_yr,
  width = 6.5,
  height = 5,
  units = "in"
)

ggsave(
  file.path(fp_figures, "zoop_LIS_flow_year_contrasts_each_sta.pdf"),
  plot = plt_gam_cont_yr,
  width = 6.5,
  height = 5,
  units = "in"
)

# Export effects plots of smooth of Week
ggsave(
  file.path(fp_figures, "zoop_LIS_flow_smooth_week.jpg"),
  plot = plt_gam_s_week,
  width = 6.5,
  height = 5,
  units = "in"
)

ggsave(
  file.path(fp_figures, "zoop_LIS_flow_smooth_week.pdf"),
  plot = plt_gam_s_week,
  width = 6.5,
  height = 5,
  units = "in"
)

# Export combined ANOVA tables for GAMs
df_gam_anova_tbl_c %>% 
  mutate(across(c("df", "F", "p_value"), ~ paste0(.x, "##"))) %>% 
  write_csv(file.path(fp_tables, "zoop_LIS_flow_GAM_anova.csv"))

# Export slopes and p-values of the modeled effects of flow by year for each station
df_gam_eff_flow_stat %>% 
  mutate(across(c("Flow_slope", "SE", "df", "t_ratio", "p_value"), ~ paste0(.x, "##"))) %>% 
  write_csv(file.path(fp_tables, "zoop_LIS_flow_GAM_eff_flow_stat.csv"))

# Export pairwise Tukey post-hoc year contrasts
df_gam_cont_yr_stat %>% 
  mutate(across(c("Estimate", "SE", "df", "t_ratio", "p_value"), ~ paste0(.x, "##"))) %>% 
  write_csv(file.path(fp_tables, "zoop_LIS_flow_GAM_year_contrasts_stat.csv"))
```