```{r}
# C-WQ Regressions for Hypotheis Table
# Author: Sarah Perry
```

```{r functions}
# import function
ndfa_action_periods2 <- function(df, na_action_remove = TRUE, keep_action_dates = FALSE) {
  # Make sure Date variable exists in df
  assert_that(
    "Date" %in% names(df),
    msg = "ndfa_action_periods function\nDataframe requires a 'Date' variable that represents sample dates in the date data type (yyyy-mm-dd)."
  )

    # Make sure Date variable in df is date data type
  assert_that(
    is.date(df$Date),
    msg = "ndfa_action_periods function\n'Date' variable must be in the date data type (yyyy-mm-dd)."
  )
  
  # Import dates for flow action periods
  fp_act_dates <- ndfa_abs_sp_path("Data Management/FlowDatesDesignations_45days.csv")
  df_act_dates_orig <- read_csv(fp_act_dates)
  
  # Convert date columns in df_act_dates_orig to date type
  df_act_dates_clean <- df_act_dates_orig %>% 
    mutate(across(starts_with(c("Pre", "Post")), mdy))
  
  # Add a Year variable to df if it doesn't already exist
  if (!"Year" %in% names(df)) {
    df <- df %>% mutate(Year = year(Date))
    message("Adding a Year variable to the dataframe.")
  }
  
  # Join flow action dates to df and add FlowActionPeriod variable
  df_join <- 
    left_join(df, df_act_dates_clean, by  = "Year") %>% 
    mutate(
      FlowActionPeriod = case_when(
        Date >= PreFlowStart & Date <= PreFlowEnd ~ "Before",
        Date > PreFlowEnd & Date < PostFlowStart ~ "During",
        Date >= PostFlowStart & Date <= PostFlowEnd ~ "After"
      )
    ) %>% 
    # Remove some variables from df_act_dates_clean
    dplyr::select(!c(WYType, FlowPulseType, NetFlowDays))
  
  # Remove sampling dates outside of before, during, and after flow action period window 
    # if na_action_remove is TRUE

  if (na_action_remove == TRUE) {
    df_join <- df_join %>% filter(!is.na(FlowActionPeriod))
  }

  # Remove variables from df_act_dates_clean containing the flow action dates if 
    # keep_action_dates is FALSE
  if (keep_action_dates == FALSE) {
    df_join <- df_join %>% dplyr::select(-c(PreFlowStart, PreFlowEnd, PostFlowStart, PostFlowEnd))
  }

  return(df_join)
}
```

```{r, message=FALSE}
# import packages
library(tidyverse)
library(DataCombine)
library(reshape2)
library(lmerTest)
library(emmeans)
library(car)
source('global_ndfa_funcs.R')
source('Water_Quality/global_wq_funcs.R')

# import data
fp_wq <- ndfa_abs_sp_path('/WQ_Subteam/Processed_Data/Continuous/RTM_INPUT_all_2021-04-20.csv')
fp_region <- ndfa_abs_sp_path('/WQ_Subteam/Processed_Data/Continuous/NDFA_Cont_WQ_Stations.csv')

df_wq <- import_rtm_data(fp_wq, num_params = 10)
df_region <- read_csv(fp_region)

# remove excess cols in df_region
df_region <- subset(df_region, select = c(StationCode, BroadRegion))

# standardize/rename Date col
df_wq$DateTime <- as.Date(df_wq$DateTime)
df_wq <- rename(df_wq, c('Date' = 'DateTime'))

# add flow action dates
df_wq <- ndfa_action_periods2(df_wq, na_action_remove = TRUE, keep_action_dates = FALSE)

# add metadata cols
df_wq <- merge(df_wq, df_region, by = c('StationCode')) 


#remove sites we aren't including (not available for all years), create a column for year
remove <- c('SRH', 'SHR', 'SRV', 'WWT', 'DWT', 'SDI', 'SGG') #TOE, LIBCUT
df_wq <- filter(df_wq, !StationCode %in% remove)

# pivot longer
df_wq <- df_wq %>% 
  dplyr::select(!ends_with('_Qual')) %>% 
  tidyr::pivot_longer(
    cols = -c(Date, Year, StationCode, FlowActionPeriod, BroadRegion),
    names_to = 'Analyte',
    values_to = 'Result')

# convert year to character
df_wq$Year <- as.character(df_wq$Year)
df_wq <- df_wq %>% filter(!Year %in% c('2011','2012'))

# add month col
df_wq$Month <- format(df_wq$Date, '%m')

# average over day
df_wq_day <- df_wq %>%
  group_by(StationCode, BroadRegion, FlowActionPeriod, Year, Month, Analyte, Day = day(Date), DayMonYear = paste(Day, Month, Year)) %>% # Date
  summarize(Result = mean(Result, na.rm = TRUE))

df_wq_day$Month <- as.character(df_wq_day$Month)

# log transform
df_wq_day$Result <- log(df_wq_day$Result)

# create lags
df_wq_day <- slide(df_wq_day, 'Result', TimeVar = 'DayMonYear', GroupVar = c('StationCode','Analyte','Year'), NewVar = 'lag1', slideBy = -1)
df_wq_day <- slide(df_wq_day, 'lag1', TimeVar = 'DayMonYear', GroupVar = c('StationCode','Analyte','Year'), NewVar = 'lag2', slideBy = -1)
df_wq_day <- slide(df_wq_day, 'lag2', TimeVar = 'DayMonYear', GroupVar = c('StationCode','Analyte','Year'), NewVar = 'lag3', slideBy = -1)

# remove excess dfs
rm(df_region, df_wq)
```

```{r all analytes}
analytes <- 'Chla' # unique(df_wq_day$Analyte)
analytes <- subset(analytes, !(analytes %in% c('Flow', 'FlowTF', 'fDOM')))
all_reg <- list()
all_aov <- list()

for (i in seq(analytes)){
  df_temp <- df_wq_day %>%
    filter(Analyte == analytes[i])
  
  # pacf(df_temp$Result, na.action = na.pass)

  lmer_fit <- lmer(Result ~ Year + FlowActionPeriod + BroadRegion + lag1 + lag2 + lag3 + (1|StationCode), data = df_temp)
  
  # create and save pacf plots
  png(ndfa_abs_sp_path(paste0('WQ_Subteam/Plots/Discrete/PACF/00_t_',analytes[i],'_rand3.png')))
  acf(residuals(lmer_fit), na.action = na.pass, main = paste0(analytes[i],' - rand3'))
  dev.off()
  
  print('here1')

  aov_lmer <- Anova(lmer_fit, type = 'II', test.statistic = 'F')
  print('here7')
  aov_lmer$Analyte <- analytes[i]
  print('here6')
  aov_lmer$Variable <- rownames(aov_lmer)
  print('here4')
  plot(aov_lmer)
  print('here5')
  
  aov_lmer <- aov_lmer %>%
    mutate(Significance = case_when(
      `Pr(>F)` >= 0 & `Pr(>F)` < 0.001 ~ '***',
      `Pr(>F)` >= 0.001 & `Pr(>F)` < 0.01 ~ '**',
      `Pr(>F)` >= 0.01 & `Pr(>F)` < 0.05 ~ '*',
      `Pr(>F)` >= 0.05 & `Pr(>F)` < 0.1 ~ '.',
      `Pr(>F)` >= 0.1 & `Pr(>F)` < 1 ~ ' ',
      )
    )
  
  print('here')
  # lmer_rg <- ref_grid(lmer_fit)
  # lmer_emm <- emmeans(lmer_rg, specs = pairwise ~ Year:Year, adjust = 'sidak') # manually change the pairs cause I'm lazy
  # cont <- test(lmer_emm)$contrasts
  # print(lmer_emm) # to check adj method

  # cont$Analyte <- analytes[i]
  # df_cont <- cont %>%
  #   mutate(Significance = case_when(
  #     p.value >= 0 & p.value < 0.001 ~ '***',
  #     p.value >= 0.001 & p.value < 0.01 ~ '**',
  #     p.value >= 0.01 & p.value < 0.05 ~ '*',
  #     p.value >= 0.05 & p.value < 0.1 ~ '.',
  #     p.value >= 0.1 & p.value < 1 ~ ' ',
  #     )
  #   )

  # all_reg[[i]] <- df_cont
  all_aov[[i]] <- aov_lmer
  print('here2')
}

# all_reg_data <- do.call(rbind, all_reg)
all_aov_data <- do.call(rbind,all_aov)

# write_csv(all_reg_data, ndfa_abs_sp_path('WQ_Subteam/Analysis_Results/CWQ/no_SDI/cwq_emmeans_year_noSDI_0.csv'))
write_csv(all_aov_data, ndfa_abs_sp_path('WQ_Subteam/Analysis_Results/CWQ/no_SDI/1_cwq_aov_noSDI_0.csv'))
```

```{r chla only}
# df_wq_wide <- reshape(df_wq_day,
#          idvar = c('StationCode','BroadRegion','Day','Year','DayMonYear','FlowActionPeriod','Month'),
#          timevar = 'Analyte',
#          direction = 'wide')
# 
# lmer_fit <- lmer(Result.Chla ~ Month + Year + FlowActionPeriod + BroadRegion + Result.DO + Result.Turbidity + Result.SpCnd + Result.WaterTemp + lag1.Chla + lag2.Chla + lag3.Chla + (1|StationCode), data = df_wq_wide)
# 
# aov_lmer <- anova(lmer_fit, type = 'III')
# aov_lmer$Analyte <- 'Chla'
# aov_lmer$Variable <- rownames(aov_lmer)
# 
# aov_lmer <- aov_lmer %>%
#   mutate(Significance = case_when(
#     `Pr(>F)` >= 0 & `Pr(>F)` < 0.001 ~ '***',
#     `Pr(>F)` >= 0.001 & `Pr(>F)` < 0.01 ~ '**',
#     `Pr(>F)` >= 0.01 & `Pr(>F)` < 0.05 ~ '*',
#     `Pr(>F)` >= 0.05 & `Pr(>F)` < 0.1 ~ '.',
#     `Pr(>F)` >= 0.1 & `Pr(>F)` < 1 ~ ' ',
#     )
#   )
# 
# lmer_rg <- ref_grid(lmer_fit)
# lmer_emm <- emmeans(lmer_rg, specs = pairwise ~ FlowActionPeriod:FlowActionPeriod, adjust = 'tukey', pbkrtest.limit = 15000)
# cont <- test(lmer_emm)$contrasts
# 
# cont$Analyte <- 'Chla'
# df_cont <- cont %>%
#   mutate(Significance = case_when(
#     p.value >= 0 & p.value < 0.001 ~ '***',
#     p.value >= 0.001 & p.value < 0.01 ~ '**',
#     p.value >= 0.01 & p.value < 0.05 ~ '*',
#     p.value >= 0.05 & p.value < 0.1 ~ '.',
#     p.value >= 0.1 & p.value < 1 ~ ' ',
#     )
#   )
# 
# fp_region <- ndfa_abs_sp_path('WQ_Subteam/Processed_Data/Continuous/NDFA_Cont_WQ_Stations.csv')
# 
# write_csv(df_cont, ndfa_abs_sp_path('WQ_Subteam/Analysis_Results/CWQ/cwq_chla_emmeans.csv'))
# write_csv(aov_lmer, ndfa_abs_sp_path('WQ_Subteam/Analysis_Results/CWQ/cwq_chla_aov.csv'))
```
