```{r}
# LIS QA for FASTR
# Sarah Perry, Amanda Maguire, Traci Treleaven, Dave Bosworth
# contact: sarah.perry@water.ca.gov
```

```{r}
# set timezone so Datetime filtering works correctly
Sys.setenv(TZ = 'Etc/GMT+8')

# import packages and functions
library(tidyverse)
library(lubridate)
library(plotly)
source('global_ndfa_funcs.R')
source('Water_Quality/Continuous_WQ/Plots_Raw_Data/rtm_raw_plots_funcs.R')
```

```{r}
# import data
fp_rel <- 'WQ_Subteam/Processed_Data/Continuous/Filtered_Dates/RTM_OUTPUT_LIS_formatted_filt.csv'

fp_abs <- ndfa_abs_sp_path(fp_rel)

df_LIS <- import_rtm_data(fp_abs, 7)

# parse datatime
df_LIS$DateTime <- ymd_hms(df_LIS$DateTime, tz = 'Etc/GMT+8')


```

```{r}
# remove suspect points
df_LIS_QA <- df_LIS %>%
  mutate(
    pH = replace(pH, DateTime == '2014-08-21 11:45:00', NA),
    Turbidity = replace(Turbidity, DateTime == '2014-09-05 10:45:00', NA),
    Turbidity = replace(Turbidity, date(DateTime) == '2015-08-01', NA),
    Turbidity = replace(
      Turbidity, 
      DateTime > '2014-08-04 1:00:00' & DateTime < '2014-08-05 10:15:00', 
      NA
    ),
    Turbidity = replace(Turbidity, date(DateTime) == '2014-09-05', NA)
  )
```

