---
title: "Check Outlier Detection Procedure - fDOM"
author: "Dave Bosworth"
date: "1/21/2021"
output: 
  html_document: 
    code_folding: show
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Global code and functions

```{r load packages, message = FALSE, warning = FALSE}
# Load packages
library(tidyverse)
library(lubridate)
library(ODWGtools)
```

```{r load functions, message = FALSE, warning = FALSE}
# Source global NDFA functions
source("global_ndfa_funcs.R")
source("Water_Quality/global_wq_funcs.R")

# Source continuous WQ data cleaning functions
source("Water_Quality/Continuous_WQ/Data_Cleaning/rtm_test_outlier_detect_funcs.R")
```

# Import and Prepare Data

```{r import data}
# Define relative file path for processed continuous WQ data files saved on NDFA SharePoint
fp_rel_wq_proc_filt <- "WQ_Subteam/Processed_Data/Continuous/Filtered_Dates"

# Define absolute file path
fp_abs_wq_proc_filt <- ndfa_abs_sp_path(fp_rel_wq_proc_filt)

# Create a vector of all file paths for the processed continuous WQ data
rtm_wq_proc_fp <- dir(fp_abs_wq_proc_filt, full.names = T)

# Remove the file with SDI data since we will need to import that separately (import_rtm_data doesn't work with it)
rtm_wq_proc_fp_f <- str_subset(rtm_wq_proc_fp, "_SDI_", negate = TRUE)

# Create a vector of the number of parameters within each station's dataset
n_params <- c(6, 11, 10, 7, 7, 7, 6, 8, 10, 7, 6, 6, 10)

# Import processed continuous WQ data into a dataframe
rtm_wq_proc_orig <- map2_dfr(rtm_wq_proc_fp_f, n_params, .f = import_rtm_data)

# Import processed continuous WQ data for SDI
sdi_orig <- read_csv(
  file.path(fp_abs_wq_proc_filt, "RTM_OUTPUT_SDI_formatted_filt.csv"),
  col_types = paste0("ccdd", str_dup("dc", 8))
)

# Add SDI data to all other continuous WQ data
rtm_wq_proc_orig <- bind_rows(rtm_wq_proc_orig, sdi_orig)
```

```{r prepare data}
# Prepare data for outlier detection procedure
rtm_wq_proc_clean <- rtm_wq_proc_orig %>% 
  # Parse DateTime variables as datetime objects and add year variable
  mutate(
    DateTime = ymd_hms(DateTime), 
    Year = year(DateTime)
  ) %>% 
  # keep only necessary variables
  select(DateTime, Year, StationCode, fDOM) %>% 
  # remove data with NA values
  filter(!is.na(fDOM)) %>% 
  # group nest by StationCode and year
  nest(df = -c(StationCode, Year)) %>% 
  # fill in datetime values for gaps of missing data
  mutate(
    df_complete = map(
      df, 
      ~complete(.x, DateTime = seq.POSIXt(min(DateTime), max(DateTime), by = "15 min"))
    )
  )
```

# Run outlier detection procedure

```{r run outlier detect procedure fDOM}
rtm_wq_proc_od <- rtm_wq_proc_clean %>% 
  mutate(
    df_od = map(
      df_complete,
      ~mutate(
        .x,
        # Spike test - fixed thresholds c(7.5, 15)
        qual_spike = rtqc_spike(fDOM, c(7.5, 15)),
        # value increases by over 50% from the prior value
        qual_incr = outlier_test_factor(
          case_when(
            is.na(fDOM) | is.na(lag(fDOM)) | is.na(lead(fDOM)) ~ NA_integer_,
            (fDOM - lag(fDOM))/lag(fDOM) > 0.5 ~ 4L,
            TRUE ~ 1L
          )
        ),
        # value decreases by over 25% from the prior value
        qual_decr = outlier_test_factor(
          case_when(
            is.na(fDOM) | is.na(lag(fDOM)) | is.na(lead(fDOM)) ~ NA_integer_,
            (fDOM - lag(fDOM))/lag(fDOM) < -0.25 ~ 4L,
            TRUE ~ 1L
          )
        ),
        # rate of change test (using 3 standard deviations, SD is of the prior 25-hour period)
        qual_rate = rtqc_rate(fDOM, 3, 100)
      ) %>% 
        # Remove missing data values and replace qual codes that have NA values
        filter(!is.na(fDOM)) %>% 
        replace_na(
          list(
            qual_spike = "pass",
            qual_incr = "pass",
            qual_decr = "pass",
            qual_rate = "pass"
          )
        ) %>% 
        # majority scoring - 2 or more tests are suspect or fail
        mutate(across(where(is.factor), ~if_else(.x == "pass", 0L, 1L))) %>% 
        mutate(
          qual_total = rowSums(across(starts_with("qual"))),
          qual_final = outlier_test_factor(if_else(qual_total > 1, 4L, 1L))
        )
    )
  )
```

# Create Plots

```{r create plots}
# Create plots of individual years for each station
rtm_wq_proc_od_plots <- rtm_wq_proc_od %>% 
  mutate(plot_od = map(df_od, .f = outlier_final_plot, param_var = fDOM)) %>% 
  select(Year, StationCode, plot_od) %>% 
  # structure data frame for more efficient printing of plots
  nest(sta_group = c(Year, plot_od))
```

# fDOM Results {.tabset .tabset-pills}

```{r print plots, echo = FALSE, results = "asis", fig.height = 6, fig.width = 8}
for (i in 1:nrow(rtm_wq_proc_od_plots)) {
  # Create subheadings for each Station
  cat("## ", as.character(rtm_wq_proc_od_plots$StationCode[i]), " {.tabset .tabset-pills}\n\n")
  for (j in 1:nrow(rtm_wq_proc_od_plots$sta_group[[i]])) {
    # Create subheadings for each Year
    cat("### ", as.character(rtm_wq_proc_od_plots$sta_group[[i]]$Year[j]), "\n\n") 
    # Print plot
    print(rtm_wq_proc_od_plots$sta_group[[i]]$plot_od[[j]])
    cat("\n\n")  
  }
}
```

