---
title: "Visualize outlier detection results template"
author: "Dave Bosworth"
date: "12/7/2020"
output: html_document
---

## {{yr}} {.tabset .tabset-pills}

```{r filter df {{yr}}, include = FALSE}
filt_yr <- {{yr}}

df_filt <- filter(df_outlier_test_plots, yr == filt_yr)
```

### Spike test - fixed thresholds

```{r spike test fixed plot {{yr}}, echo = FALSE, fig.width = 8, fig.height = 6}
df_filt$plot_spike_fixed[[1]]
```

### Spike test - dynamic thresholds

```{r spike test dynamic plot {{yr}}, echo = FALSE, fig.width = 8, fig.height = 6}
df_filt$plot_spike_dyn[[1]]
```

### Rate of change test

```{r rate of change plot {{yr}}, echo = FALSE, fig.width = 8, fig.height = 6}
df_filt$plot_rate[[1]]
```

### Percent increase from prior value

```{r perc incr plot {{yr}}, echo = FALSE, fig.width = 8, fig.height = 6}
df_filt$plot_incr[[1]]
```

### Percent decrease from prior value

```{r perc decr plot {{yr}}, echo = FALSE, fig.width = 8, fig.height = 6}
df_filt$plot_decr[[1]]
```

### Majority scoring

```{r majority scoring plot {{yr}}, echo = FALSE, fig.width = 8, fig.height = 6}
df_filt$plot_maj[[1]]
```

