```{r}
# SDI QA for FASTR
# Sarah Perry, Amanda Maguire, Traci Treleaven, Dave Bosworth
# Contact: David.Bosworth@water.ca.gov
```

```{r}
# set timezone so Datetime filtering works correctly
Sys.setenv(TZ = 'Etc/GMT+8')

# import packages and functions
library(tidyverse)
library(lubridate)
source('global_ndfa_funcs.R')
source('Water_Quality/Continuous_WQ/Plots_Raw_Data/rtm_raw_plots_funcs.R')
```

```{r}
# import data
fp_rel <- 'WQ_Subteam/Processed_Data/Continuous/Filtered_Dates/RTM_OUTPUT_SDI_formatted_filt.csv'

fp_abs <- ndfa_abs_sp_path(fp_rel)

df_SDI <- read_csv(
    file = fp_abs,
    col_types = paste0("ccdd", str_dup("dc", 8))
  )

# parse datatime
df_SDI$DateTime <- ymd_hms(df_SDI$DateTime, tz = 'Etc/GMT+8')
```

```{r}
# remove suspect points - a few spikes in the DO values
df_SDI_QA <- df_SDI %>%
  mutate(
    DO = replace(
      DO, 
      DateTime >= '2018-10-02 8:15:00' & DateTime <= '2018-10-02 9:00:00' |
      DateTime == '2019-08-06 8:30:00' |
      DateTime >= '2019-09-17 9:45:00' & DateTime <= '2019-09-17 10:30:00', 
      NA
    ),
    DO_Qual = replace(
      DO_Qual, 
      DateTime >= '2018-10-02 8:15:00' & DateTime <= '2018-10-02 9:00:00' |
      DateTime == '2019-08-06 8:30:00' |
      DateTime >= '2019-09-17 9:45:00' & DateTime <= '2019-09-17 10:30:00', 
      "unreliable"
    )
  )
```

