---
title: "Discrete WQ - flow action periods"
author: "Dave Bosworth"
date: "10/29/2020"
output: 
  html_document: 
    code_folding: hide
    toc: true
    toc_depth: 1
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.kable.NA = "")
```

# Global code and functions

```{r load packages, message = FALSE, warning = FALSE}
# Load packages
library(tidyverse)
library(lubridate)
library(scales)
library(kableExtra)
```

```{r load functions, message = FALSE, warning = FALSE}
# Source global WQ functions
source("Water_Quality/global_wq_funcs.R")
```

```{r define file paths}
# define main FASTR filepath (assumes sync'd with Sharepoint)
fp_fastr <- 'California Department of Water Resources/North Delta Flow Action - Documents/'

# define relative filepaths 
fp_rel_dwq <- paste0(fp_fastr,'WQ_Subteam/Processed_Data/Discrete/WQ_OUTPUT_Discrete_Lab_formatted.csv')
fp_rel_dates <- paste0(fp_fastr,'Data Management/FlowDatesDesignations_45days.csv')

# define absolute filepaths
fp_abs_dwq <- get_abs_path(fp_rel_dwq)
fp_abs_dates <- get_abs_path(fp_rel_dates)
```

# Import and Prepare Data

```{r import data, message = FALSE}
# Import data
df_dwq_orig <- read_csv(fp_abs_dwq)
df_dates_orig <- read_csv(fp_abs_dates)
```

```{r prepare data, message = FALSE}
# Parse dates in df_dates_orig
df_dates_clean <- df_dates_orig %>% 
  mutate_at(vars(starts_with(c("Pre", "Post"))), mdy)

# Define stations to remove
sta_remove <- c("DWT", "SRH", "SDI", "SHR", "SRV", "WWT", "LIS", "STTD")

# Clean original discrete lab data
df_dwq_clean <- df_dwq_orig %>% 
  # subset stations and analytes
  filter(
    #!StationCode %in% sta_remove,
    Analyte %in% c("Chla", "DisAmmonia")
  ) %>% 
  # parse date-time variable and add date and year variables
  mutate(
    DateTime = ymd_hms(DateTime),
    Date = date(DateTime),
    Year = year(DateTime)
  ) %>% 
  # add dates for flow actions
  left_join(df_dates_clean) %>% 
  # create ActionPhase variable
  mutate(
    ActionPhase = case_when(
      Date >= PreFlowStart & Date <= PreFlowEnd ~ 'Pre',
      Date > PreFlowEnd & Date < PostFlowStart ~ 'During',
      Date >= PostFlowStart & Date <= PostFlowEnd ~ 'Post',
      TRUE ~ "Excluded"
    ),
    ActionPhase = factor(ActionPhase, levels = c("Pre", "During", "Post", "Excluded"))
  )
```


# Create Plots

```{r create plots and kables}
# Create function for discrete WQ plots
create_dwq_plot <- function(df) {
  df %>% 
    ggplot(aes(x = Date, y = Result, color = ActionPhase)) +
    geom_point() +
    facet_grid(rows = vars(StationCode)) +
    scale_x_date(
      name = "Date",
      breaks = breaks_pretty(15),
      labels = label_date_short()
    )
}

# Create plots and kables for each year-analyte combination
df_dwq_plots_tbls <- df_dwq_clean %>% 
  nest(data = -c(Year, Analyte)) %>% 
  mutate(
    plot = map(data, .f = create_dwq_plot),
    table = map(
      data, 
      ~count(.x, StationCode, ActionPhase) %>% 
        pivot_wider(names_from = ActionPhase, values_from = n) %>% 
        kable(
          format = "html",
          caption = "Sample counts within each Action Phase"
        ) %>% 
        kable_styling(
          "striped", 
          full_width = FALSE, 
          position = "left"
        )
    )
  ) %>% 
  nest(data2 = -Year)
```


# Plots and Data Summaries {.tabset .tabset-fade .tabset-pills}

```{r print plots and kables, echo = FALSE, results = "asis", fig.height = 9, fig.width = 8}
for (i in 1:nrow(df_dwq_plots_tbls)) {
  # Create heading for each parameter
  cat("## ", as.character(df_dwq_plots_tbls$Year[i]), " {.tabset .tabset-pills}\n\n")
  for (j in 1:nrow(df_dwq_plots_tbls$data2[[i]])) {
    # Create subheadings for each yr
    cat("### ", as.character(df_dwq_plots_tbls$data2[[i]]$Analyte[j]), "\n\n") 
    # Display plot
    print(df_dwq_plots_tbls$data2[[i]]$plot[[j]])
    cat("\n\n")
    # Display kable
    print(df_dwq_plots_tbls$data2[[i]]$table[[j]])
    cat("\n\n")
  }
}
```

