```{r}
# FASTR - Discrete WQ Boxplots
# purpose: boxplots discrete WQ data for outlier detection
# author: Sarah Perry
# contact: seperry83@gmail.com
```

```{r message=FALSE, warning=FALSE}
# import packages
library(ggplot2)
library(tidyverse)
library(NADA)

# source functions
source('d-wq_boxplots_funcs.R')
```

```{r message=FALSE, warning=FALSE}
# --- Import Data ---
# define main FASTR filepath (assumes sync'd with Sharepoint)
fp_fastr <- 'California Department of Water Resources/Office of Water Quality and Estuarine Ecology - North Delta Flow Action/'

# define relative filepaths 
fp_rel_wq <- paste(fp_fastr,'WQ_Subteam/Processed_Data/Discrete/Discrete_Output_Lab.csv', sep = '')
fp_rel_dates <- paste(fp_fastr,'Data Management/FlowDatesDesignations.csv', sep = '')

# define absolute filepaths
fp_abs_wq <- get_abs_path(fp_rel_wq)
fp_abs_dates <- get_abs_path(fp_rel_dates)

# read in data
df_wq <- read_csv(fp_abs_wq)
df_dates <- read_csv(fp_abs_dates)

# --- Clean Data In Order To Create Boxplots w/ RLs ---
# create date/year columns (character type)
df_wq$Date <- format(strptime(df_wq$DateTime, '%m/%d/%Y'),'%m/%d/%Y')
df_wq$Year <- format(strptime(df_wq$DateTime, '%m/%d/%Y'),'%Y')

# add full analyte name column
df_wq <- add_analyte_names(df_wq)

# add in phase actions (will also convert 'Date' column to date type)
df_wq <- add_phase_actions(df_wq, df_dates)

#add 'full group' column (ie. station + year), set as factor type
df_wq$FullGroup <- paste(df_wq$StationCode, df_wq$Year, df_wq$Analyte, sep = ',')

# change values in LabDetect column to boolean (censored = TRUE)
df_wq$LabDetect <- ifelse(df_wq$LabDetect == 'Non-detect', TRUE, FALSE)
# df_wq$Result[df_wq$LabDetect == TRUE] <- NA
```


```{r message=FALSE, warning=FALSE}
# --- Prep for Graphs ---
# list of analytes/stations
analytes <- unique(df_wq$Analyte)
stations <- unique(df_wq$StationCode)

# --- Create BoxPlot --
source('d-wq_boxplots_funcs.R')
# create plots
for (analyte in analytes){ 
  bp <- cen_boxplt(df_wq)

  # save graphs
  fp_rel_save <- paste(fp_fastr,'WQ_Subteam/Raw_Plots/Discrete/Boxplots', sep = '')
  fp_abs_save <- get_abs_path(fp_rel_save)
  
  ggsave(
    paste(fp_abs_save,'/Boxplots_',analyte,'.png',sep = ''),
    bp,
    width = 10,
    height = 11,
    unit = 'in'
     )
}


  # 
  # # create boxplot
  # plts <- mapply(
  #   station = stations,
  #   color_scheme = colors,
  #   FUN = function(x, station, color_scheme) cen_boxplt(df_wq, station),
  #   SIMPLIFY = FALSE
  #   )

    # # create boxplot
    # bp <- ggplot(df_filt, aes(x=FullGroup, y=Result, group=FullGroup)) +
    #   geom_boxplot(aes(fill=FullGroup))
    # print(bp)
    # break
```
```{r}
fp_abs_save
```

```{r}
library(stats)
IQR(bp$Data, na.rm = TRUE)
boop <- bp
summary(boop$Data)
#subset(bp, bp$Data < quantile(bp$Data, probs= 0.05) | quantile(bp$Data, probs=0.95) < bp$Data)
```


```{r}
source('d-wq_boxplots_funcs.R')

data(Golden)
with(Golden, cen_boxplt(Blood, BloodCen, DosageGroup))

unique(df_wq$StationCode)

obs[group == "LIB,2019,Chla"]
all(!cen[group == "LIB,2019,Chla"])

length(cen[group == "LIB,2019,Chla"]) > 1
```

```{r}
df_wq[df_wq$StationCode == 'BL5' & df_wq$Analyte == 'DOC' & df_wq$Year == 2018,]
```
```{r}
any(cen[group == "LIS,2013,DisAmmonia"]) # if any are censored data (ie. are any/all TRUE)

x <- c(TRUE, TRUE, TRUE)

y <- !x
x
y
```

