```{r}
# import packages
library(tidyverse)
library(lubridate)
library(glue)
source('global_ndfa_funcs.R')
source('Water_Quality/global_wq_funcs.R')
source('Water_Quality/Discrete_WQ/outlier_detection/d-wq_boxplots_funcs.R')

# define main FASTR filepath (assumes sync'd with Sharepoint)
fp_fastr <- 'California Department of Water Resources/North Delta Flow Action - Documents/'

# define relative filepaths 
fp_rel_wq <- paste(fp_fastr,'WQ_Subteam/Processed_Data/Discrete/WQ_INPUT_Discrete_Lab_2021-01-25.csv', sep = '')
fp_rel_dates <- paste(fp_fastr,'Data Management/FlowDatesDesignations_45days.csv', sep = '')
fp_rel_regions = paste0(fp_fastr, 'WQ_Subteam/Processed_Data/Discrete/Analysis/NDFA_map.csv')

# define absolute filepaths
fp_abs_wq <- get_abs_path(fp_rel_wq)
fp_abs_dates <- get_abs_path(fp_rel_dates)
fp_abs_regions <- get_abs_path(fp_rel_regions)

# read in data
df_wq <- read_csv(fp_abs_wq, col_types = "ccccccnncc") 
df_dates <- read_csv(fp_abs_dates)
df_regions <- read_csv(fp_abs_regions)

# --- Clean Data In Order To Create Boxplots w/ RLs ---
# create date/year columns
df_wq <- df_wq %>% 
  mutate(
    DateTime = ymd_hms(DateTime),
    Date = date(DateTime),
    Year = year(DateTime)
  )

df_regions <- df_regions %>% rename(StationCode = Station)
df_wq <- merge(x = df_wq, y = df_regions[, c('StationCode', 'BroadRegion')], by = 'StationCode')

# add full analyte name column
df_wq <- add_analyte_names(df_wq)

# add in flow action periods
df_wq <- ndfa_action_periods(df_wq)

#add 'full group' column (ie. station + year)
df_wq$Year <- as.character(df_wq$Year)
df_wq$FullGroup <- paste(df_wq$StationCode, df_wq$Year, df_wq$Analyte, sep = ',')
df_wq$Year <- as.double(df_wq$Year)

# change values in LabDetect column to boolean (censored = TRUE)
df_wq$LabDetect[df_wq$Result == '< RL'] <- 'Non-detect'
df_wq$LabDetect[df_wq$Result == '< MDL'] <- 'Non-detect'
df_wq$Result[df_wq$LabDetect == 'Non-detect'] <- NA
df_wq$Result <- as.numeric(df_wq$Result)
df_wq$LabDetect <- ifelse(df_wq$LabDetect == 'Non-detect', TRUE, FALSE)
df_wq$LabDetect[is.na(df_wq$LabDetect)] <- FALSE
df_wq$AnalyteFull[df_wq$AnalyteFull == 'Dissolved Oraganic Carbon'] <- 'Dissolved Organic Carbon'

rm(df_regions, df_dates)
```

```{r}
blank_theme <- function(){
  theme_bw() +
    theme(
      panel.grid.major.y = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.y = element_blank(),
      panel.grid.minor.x = element_blank(),
      axis.text = element_text(color = 'black', size = 12, family = 'sans'),
      axis.text.x = element_text(vjust=0.5, margin = margin(t = 1)),
      axis.title = element_text(size = 14),
      strip.text = element_text(size = 9),
      plot.title = element_text(size = 16, hjust = 0.5),
      legend.position='right',
      legend.title = element_text(size = 14),
      legend.text=element_text(size=12),
      legend.box.margin=margin(-5,0,-5,0)
     # legend.background = element_rect(color = 'black')
    )
}

is_outlier <- function(x) {
  outlier <- (x < quantile(x, 0.25) - 1.5 * IQR(x) | x > quantile(x, 0.75) + 1.5 * IQR(x))
  
  return(outlier)
}
```

```{r}
df_wq$Result[df_wq$Result >= 100 & df_wq$AnalyteFull == 'Dissolved Organic Carbon'] <- NA

# Only include data from 2013-2019 and non-NA values
df_wq <- filter(df_wq, Year > 2012, !is.na(Result))

analytes <- unique(df_wq$AnalyteFull)
df_wq$Year <- as.factor(df_wq$Year)
df_wq$FlowActionPeriod <- factor(df_wq$FlowActionPeriod, levels = c('Before','During','After'))
df_wq$BroadRegion <- factor(df_wq$BroadRegion, levels = c('Upstream','Downstream'))

for (analyte in analytes){
  df_filt <-
    df_wq %>%
    filter(
      AnalyteFull == analyte)

  plt <- df_filt %>% 
    ggplot(aes(FlowActionPeriod, Result, fill = FlowActionPeriod)) +
    geom_violin(draw_quantiles = c(0.25, 0.5, 0.75), alpha = 0.75) +
    facet_wrap(vars(BroadRegion), scales = "free") +
    ggtitle(analyte) + 
    blank_theme() +
    xlab("Flow Pulse Period") +
    ylab(df_filt$Units) +
    scale_fill_viridis_d("Flow Pulse\nPeriod:", option = 'plasma', begin = 0.3)
  
  print(plt)
  
  fp_plots <- get_abs_path(paste0(fp_fastr,'WQ_Subteam/Plots/Discrete/Violin_Plots/Std_Units/violin_',analyte,'.png'))
  
  ggsave(fp_plots, width = 7, height = 4.25, units = "in")
}
```

```{r plots log transform}
df_wq <- df_wq %>% mutate(Result_log = log(Result))

for (analyte in analytes){
  df_filt <-
    df_wq %>%
    filter(
      AnalyteFull == analyte)

  plt <- df_filt %>% 
    ggplot(aes(FlowActionPeriod, Result_log, fill = FlowActionPeriod)) +
    geom_violin(draw_quantiles = c(0.25, 0.5, 0.75), alpha = 0.75) +
    facet_wrap(vars(BroadRegion)) +
    ggtitle(analyte) + 
    blank_theme() +
    xlab("Flow Pulse Period") +
    ylab(glue("log({df_filt$Units})")) +
    scale_fill_viridis_d("Flow Pulse\nPeriod:", option = 'plasma', begin = 0.3)
  
  print(plt)
  
  fp_plots <- get_abs_path(paste0(fp_fastr,'WQ_Subteam/Plots/Discrete/Violin_Plots/log_Units/violin_',analyte,'_log.png'))
  
  ggsave(fp_plots, width = 7, height = 4.25, units = "in")
}
```

