---
title: "NDFS Contaminants Manuscript"
subtitle: "Explore 2017-2020 Pesticide Use Data"
author: "Dave Bosworth"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document: 
    code_folding: show
    toc: true
    toc_float:
      collapsed: false
editor_options: 
  chunk_output_type: console
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = here::here("docs"),
      envir = globalenv()
    )
    })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Purpose

Create some plots to explore the 2017-2020 pesticide use data for the Sacramento River and Yolo Bypass regions.

# Global code and functions

```{r load packages, message = FALSE, warning = FALSE}
# Load packages
library(tidyverse)
library(scales)
library(here)
```

# Import and Prepare Data

```{r import data}
df_pest_use <- readRDS(here("manuscript_contam/data/processed/pesticide_use_daily_tot_2017-2020.rds"))
```

```{r prepare data}
df_pest_use_c <- df_pest_use %>% 
  mutate(
    PesticideClass = factor(PesticideClass, levels = c("Rice", "Pyrethroid", "Other")),
    DOY = yday(Date),
  )
```

# Plots

## Daily totals

```{r plot daily tot, fig.width = 8, fig.height = 6}
df_pest_use_c %>% 
  ggplot(aes(x = DOY, y = TotalApplication, fill = PesticideClass)) +
  geom_col() +
  facet_grid(rows = vars(Year), cols = vars(Region)) +
  scale_fill_viridis_d(
    name = "Pesticide Class", 
    option = "plasma", 
    end = 0.8
  ) +
  scale_y_continuous(
    name = "Total Application (lbs)",
    labels = label_comma()
  ) +
  theme_bw() +
  theme(legend.position = "top")
```

# Monthly Totals

```{r plot monthly tot, fig.width = 8, fig.height = 6}
df_pest_use_c %>% 
  summarize(
    TotalApplication = sum(TotalApplication),
    .by = c(Region, Month, Year, PesticideClass)
  ) %>% 
  ggplot(aes(x = Month, y = TotalApplication, fill = PesticideClass)) +
  geom_col() +
  facet_grid(rows = vars(Year), cols = vars(Region)) +
  scale_fill_viridis_d(
    name = "Pesticide Class", 
    option = "plasma", 
    end = 0.8
  ) +
  scale_y_continuous(
    name = "Total Application (lbs)",
    labels = label_comma()
  ) +
  theme_bw() +
  theme(legend.position = "top")
```

