---
title: "NDFA Contaminants Data: EPA Benchmark Exceedences"
author: "Dave Bosworth"
date: "3/11/2021"
output: 
  html_document: 
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Purpose

Produce a simple bar plot showing the number of EPA benchmark exceedances for the contaminant concentrations in water data set collected for the NDFA project. Includes data collected from 2015-2019 and benchmarks for acute and chronic toxicity for both fish and invertebrates.

# Global code and functions

```{r load packages, message = FALSE, warning = FALSE}
# Load packages
library(tidyverse)
library(lubridate)
library(here)
```

# Import and Prepare Data

```{r import data, message = FALSE}
# Define file path of Contaminants directory
fp_contam <- here("Water_Quality/Contaminants")

# Create vector of file paths for the csv files containing EPA benchmark
  # exceedance data within the Contaminants directory
dir_epa_exceed <- dir(fp_contam, pattern = "toxicity\\.csv$", full.names = TRUE)

# Import 4 csv files
lst_epa_exceed <- map(dir_epa_exceed, read_csv)
```

```{r prepare data}
# Combine and prepare data for plot
df_epa_exceed <- lst_epa_exceed %>% 
  map(~ select(.x, -...1)) %>% 
  reduce(full_join, by = c("Year", "FlowPeriod")) %>% 
  rename_with(~str_remove(.x, "^N_"), starts_with("N_")) %>% 
  mutate(FlowPeriod = factor(FlowPeriod, levels = c("Before", "During", "After"))) %>% 
  pivot_longer(
    cols = starts_with(c("acute", "chronic")),
    names_to = "Benchmark", 
    values_to = "Exceedances"
  ) %>% 
  drop_na(Exceedances)
```

# Create Plot

```{r create plot}
df_epa_exceed %>% 
  ggplot(aes(FlowPeriod, Exceedances)) +
  geom_col() +
  facet_grid(cols = vars(Benchmark), rows = vars(Year))
```

