---
title: "NDFA Contaminants Data: Cleaning"
author: "Dave Bosworth"
date: "8/31/2020"
output: 
  html_document: 
    code_folding: show
    toc: true
    toc_depth: 4
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Purpose

This document provides the code and decisions made to clean and standardize all contaminants data used for the North Delta Flow Action synthesis project. The data were collected by USGS, and includes concentration data for water, suspended sediment, and zooplankton samples.

# Global code and functions

```{r load packages, message = FALSE, warning = FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
```

```{r load functions}
# Source global WQ functions
source("Water_Quality/global_wq_funcs.R")

# Source continuous WQ data cleaning functions
source("Water_Quality/Continuous_WQ/Data_Cleaning/rtm_clean_data_funcs.R")
```

```{r define file paths}
# Define main NDFA file path for WQ subteam (assumes synced with SharePoint)
fp_fastr <- "California Department of Water Resources/Office of Water Quality and Estuarine Ecology - North Delta Flow Action/WQ_Subteam/"

# Define relative file paths for raw and processed continuous WQ data files
fp_rel_wq_raw <- paste0(fp_fastr, "Raw_Data/Continuous")
fp_rel_wq_proc <- paste0(fp_fastr, "Processed_Data/Continuous")

# Define absolute file paths
fp_abs_wq_raw <- get_abs_path(fp_rel_wq_raw)
fp_abs_wq_proc <- get_abs_path(fp_rel_wq_proc)

# Clean up
rm(fp_rel_wq_raw, fp_rel_wq_proc)

# Create a vector of object names to keep throughout the script
obj_keep <- append(objects(), "obj_keep")
```

```{r set system tz as PST}
# Set System Timezone as "Etc/GMT+8" (PST) to make it consistent with all df's 
Sys.setenv(TZ = "Etc/GMT+8")
```

# USGS Data

## Import Data

```{r import raw usgs data}
# Create a vector of all file paths for the raw USGS continuous data
usgs_fp <- dir(fp_abs_wq_raw, pattern = "USGS", full.names = T)

# Remove the .xlsx file with SDI flow data since we will need to import that separately (all other files are .csv)
usgs_fp_f <- discard(usgs_fp, str_detect(usgs_fp, ".xlsx$"))

# Create a tibble of all raw USGS continuous data file paths
usgs_files <- tibble(
  filepath = usgs_fp_f,
  n_params = c(18, 10, 4, 6, 11, 10, 11, 7, 10, 3)
)

# Import USGS data into a nested dataframe
usgs_orig <- usgs_files %>% 
  mutate(
    sta_code = str_sub(filepath, start = 176, end = -5),
    df = map2(filepath, n_params, .f = import_usgs_data)
  ) %>% 
  select(sta_code, df)

# Import flow data for SDI
sdi_flow_orig <- read_excel(paste0(fp_abs_wq_raw, "/RTM_RAW_USGS_SDI Flow_2011-2018.xlsx"))
```



