```{r}
# STTD QA for FASTR
# Sarah Perry, Amanda Maguire, Traci Treleaven, Dave Bosworth
# contact: sarah.perry@water.ca.gov
```

```{r}
# set timezone so Datetime filtering works corerctly
Sys.setenv(TZ = 'Etc/GMT+8')
```

```{r}
# import packages and functions
library(tidyverse)
library(lubridate)
library(plotly)
source('global_ndfa_funcs.R')
source('Water_Quality/Continuous_WQ/Plots_Raw_Data/rtm_raw_plots_funcs.R')
```

```{r}
# import data
fp_rel <- 'WQ_Subteam/Processed_Data/Continuous/Filtered_Dates/RTM_OUTPUT_STTD_formatted_filt.csv'

fp_abs <- ndfa_abs_sp_path(fp_rel)

df_STTD <- import_rtm_data(fp_abs,6)

# parse datatime
df_STTD$DateTime <- ymd_hms(df_STTD$DateTime, tz = 'Etc/GMT+8')
```

```{r}
# remove suspect points
df_STTD <- df_STTD %>%
  mutate(
    DO = replace(DO, DO == min(DO, na.rm = TRUE), NA),
    DO = replace(DO, DO == min(DO, na.rm = TRUE), NA),
    DO = replace(DO, DateTime == '2017-08-10 11:30:00', NA),
    SpCnd = replace(SpCnd, DateTime == '2013-09-27 8:15:00', NA)
    )
```

```{r}
# check via plots
df_plot <- df_STTD %>% filter(year(DateTime) == 2013)

plt <- ggplot(data = df_plot, aes(x = DateTime, y = SpCnd)) + geom_line()

ggplotly(plt)
```



