```{r}
# FASTR D-WQ ANOVAs
# Author: Sarah Perry
# Date created: 01/27/2020
# Purpose: ANOVAS for D-WQ

# import packages and scripts
library(tidyverse)
library(lubridate)
library(lmerTest)
library(rstatix)
library(lme4)
library(car)
# library(ARTool)
source('global_ndfa_funcs.R')
```

```{r Import Data}
# define absolute filepaths
fp_abs_discrete <- ndfa_abs_sp_path('WQ_Subteam/Processed_Data/Discrete/WQ_INPUT_Discrete_Lab_2021-01-25.csv')
fp_abs_wy <- ndfa_abs_sp_path('WQ_Subteam/Processed_Data/Discrete/Analysis/FlowDatesDesignations_45days.csv')
fp_abs_region <- ndfa_abs_sp_path('WQ_Subteam/Processed_Data/Discrete/Analysis/NDFA_map.csv')

# read in data
df_discrete <- read_csv(fp_abs_discrete)
df_water_year <- read_csv(fp_abs_wy)
df_region <- read_csv(fp_abs_region)

# remove excess cols in df_region
df_region <- subset(df_region, select = c(Station, BroadRegion))

#remove sites we aren't including (not available for all years), create a column for year
remove <- c('DWT', 'SRH', 'SDI', 'SHR', 'SRV', 'WWT', 'RMB')
df_discrete <- filter(df_discrete, !StationCode %in% remove)

# standardize/rename Date col
df_discrete$DateTime <- as.Date(df_discrete$DateTime)
df_discrete <- rename(df_discrete, c('Date' = 'DateTime'))

# rename Station col
df_discrete <- rename(df_discrete, c('Station' = 'StationCode'))

# add flow action dates
df_discrete <- ndfa_action_periods(df_discrete, na_action_remove = TRUE, keep_action_dates = FALSE)

# add metadata cols
df_wq <- merge(df_discrete, df_water_year, by = c('Year')) 
df_wq <- merge(df_wq, df_region, by = c('Station')) 

# standardize names
df_wq$Result[df_wq$Result == '< MDL' | df_wq$Result == '< RL'] <- NA
df_wq$Result <- as.numeric(df_wq$Result)


# rm extra dfs
rm(df_water_year, df_region, df_discrete)

# list of analytes
analytes <- unique(df_wq$Analyte)

# average over stations/year
df_wq <- df_wq %>%
  group_by(Station, Year, FlowActionPeriod, BroadRegion, RL, Analyte) %>%
  summarize(Result = mean(Result, na.rm = TRUE)) %>%
  ungroup()
```

- need to account for unbalanced design (type 3 or different combos)
- want to do two-way interactions or less
- need to account for NDs (run different combinations)



- run in each order to account for unbalanced design
    - REML - can include the two-way interactions, can include station as an error term/nested error term
    - ** aov can't handle random error terms if unbalanced design

```{r ANOVA - set to RL}
aov_all <- list()

for (i in seq(analytes)){
  analyte <- analytes[i]
  
  print(paste0('~*~*~',analyte,'~*~*~'))
  
  df_sub <- df_wq %>% filter(Analyte == analyte & !Year %in% c('2011','2012'))
  
  df_sub$Result <- with(df_sub, ifelse(is.na(Result), RL, Result))

  df_sub$Result <- log(df_sub$Result)
  
  lmer_fit <- lmer(Result ~ Year + FlowActionPeriod + BroadRegion + (1|BroadRegion:Station), data = df_sub)
  
  aov_lmer <- anova(lmer_fit, type = 'III')

  df_aov <- as.data.frame(aov_lmer)
  df_aov <- rename(df_aov, Pr_F = `Pr(>F)`)
  df_aov$Analyte <- analyte
  df_aov <- df_aov %>%
    mutate(Significance = case_when(
      Pr_F >= 0 & Pr_F < 0.001 ~ '***',
      Pr_F >= 0.001 & Pr_F < 0.01 ~ '**',
      Pr_F >= 0.01 & Pr_F < 0.05 ~ '*',
      Pr_F >= 0.05 & Pr_F < 0.1 ~ '.',
      Pr_F >= 0.1 & Pr_F < 1 ~ ' ',
      )
    )
  df_aov <- rename(df_aov, `Pr(>F)` = Pr_F)

  aov_all[[i]] <- df_aov

}

all_data <- do.call(rbind, aov_all)
all_data
write_csv(all_data, 'C:/Users/sperry/Desktop/anova_RL.csv')
```

```{r ANOVA - set to ~0}
aov_all <- list()

for (i in seq(analytes)){
  analyte <- analytes[i]
  df_sub <- df_wq %>% filter(Analyte == analyte & !Year %in% c('2011','2012'))
  
  df_sub$Result[is.na(df_sub$Result)] <- 0.01
  df_sub$Result <- log(df_sub$Result)

  lmer_fit <- lmer(Result ~ Year + FlowActionPeriod + BroadRegion + (1|BroadRegion:Station), data = df_sub)
  
  aov_lmer <- anova(lmer_fit, type = 'III')

  df_aov <- as.data.frame(aov_lmer)
  df_aov <- rename(df_aov, Pr_F = `Pr(>F)`)
  df_aov$Analyte <- analyte
  df_aov <- df_aov %>%
    mutate(Significance = case_when(
      Pr_F >= 0 & Pr_F < 0.001 ~ '***',
      Pr_F >= 0.001 & Pr_F < 0.01 ~ '**',
      Pr_F >= 0.01 & Pr_F < 0.05 ~ '*',
      Pr_F >= 0.05 & Pr_F < 0.1 ~ '.',
      Pr_F >= 0.1 & Pr_F < 1 ~ ' ',
      )
    )
  df_aov <- rename(df_aov, `Pr(>F)` = Pr_F)

  aov_all[[i]] <- df_aov
}

all_data <- do.call(rbind, aov_all)
write_csv(all_data, 'C:/Users/sperry/Desktop/anova_0.csv')
```

```{r ANOVA - random sub 1}
set.seed(1)
aov_all <- list()

for (i in seq(analytes)){
  analyte <- analytes[i]
  
  df_sub <- df_wq %>% filter(Analyte == analyte & !Year %in% c('2011','2012'))
  df_sub$Result <- log(df_sub$Result)

  lmer_fit <- lmer(Result ~ Year + FlowActionPeriod + BroadRegion + (1|BroadRegion:Station), data = df_sub)
  
  aov_lmer <- anova(lmer_fit, type = 'III')

  df_aov <- as.data.frame(aov_lmer)
  df_aov <- rename(df_aov, Pr_F = `Pr(>F)`)
  df_aov$Analyte <- analyte
  df_aov <- df_aov %>%
    mutate(Significance = case_when(
      Pr_F >= 0 & Pr_F < 0.001 ~ '***',
      Pr_F >= 0.001 & Pr_F < 0.01 ~ '**',
      Pr_F >= 0.01 & Pr_F < 0.05 ~ '*',
      Pr_F >= 0.05 & Pr_F < 0.1 ~ '.',
      Pr_F >= 0.1 & Pr_F < 1 ~ ' ',
      )
    )
  df_aov <- rename(df_aov, `Pr(>F)` = Pr_F)

  aov_all[[i]] <- df_aov
}

all_data <- do.call(rbind, aov_all)
write_csv(all_data, 'C:/Users/sperry/Desktop/anova_rand1.csv')
```

```{r ANOVA - random sub 2}
set.seed(2)
aov_all <- list()

for (i in seq(analytes)){
  analyte <- analytes[i]
  
  df_sub <- df_wq %>% filter(Analyte == analyte & !Year %in% c('2011','2012'))
  df_sub$Result <- log(df_sub$Result)

  lmer_fit <- lmer(Result ~ Year + FlowActionPeriod + BroadRegion + (1|BroadRegion:Station), data = df_sub)
  
  aov_lmer <- anova(lmer_fit, type = 'III')

  df_aov <- as.data.frame(aov_lmer)
  df_aov <- rename(df_aov, Pr_F = `Pr(>F)`)
  df_aov$Analyte <- analyte
  df_aov <- df_aov %>%
    mutate(Significance = case_when(
      Pr_F >= 0 & Pr_F < 0.001 ~ '***',
      Pr_F >= 0.001 & Pr_F < 0.01 ~ '**',
      Pr_F >= 0.01 & Pr_F < 0.05 ~ '*',
      Pr_F >= 0.05 & Pr_F < 0.1 ~ '.',
      Pr_F >= 0.1 & Pr_F < 1 ~ ' ',
      )
    )
  df_aov <- rename(df_aov, `Pr(>F)` = Pr_F)

  aov_all[[i]] <- df_aov
}

all_data <- do.call(rbind, aov_all)
write_csv(all_data, 'C:/Users/sperry/Desktop/anova_rand2.csv')
```

```{r ANOVA - random sub 3}
set.seed(3)
aov_all <- list()

for (i in seq(analytes)){
  analyte <- analytes[i]
  
  df_sub <- df_wq %>% filter(Analyte == analyte & !Year %in% c('2011','2012'))
  df_sub$Result <- log(df_sub$Result)

  lmer_fit <- lmer(Result ~ Year + FlowActionPeriod + BroadRegion + (1|BroadRegion:Station), data = df_sub)
  
  aov_lmer <- anova(lmer_fit, type = 'III')

  df_aov <- as.data.frame(aov_lmer)
  df_aov <- rename(df_aov, Pr_F = `Pr(>F)`)
  df_aov$Analyte <- analyte
  df_aov <- df_aov %>%
    mutate(Significance = case_when(
      Pr_F >= 0 & Pr_F < 0.001 ~ '***',
      Pr_F >= 0.001 & Pr_F < 0.01 ~ '**',
      Pr_F >= 0.01 & Pr_F < 0.05 ~ '*',
      Pr_F >= 0.05 & Pr_F < 0.1 ~ '.',
      Pr_F >= 0.1 & Pr_F < 1 ~ ' ',
      )
    )
  df_aov <- rename(df_aov, `Pr(>F)` = Pr_F)

  aov_all[[i]] <- df_aov
}

all_data <- do.call(rbind, aov_all)
write_csv(all_data, 'C:/Users/sperry/Desktop/anova_rand3.csv')
```