---
title: 'NDFA - Discrete WQ Time Series'
author: 'Sarah Perry'
date: '09/10/2020'

output:
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 1
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Purpose

This file provides time series graphs for the discrete water quality stations of the FASTR project. They include time periods before, during, and after a flow action.

# Code {.tabset .tabset-fade .tabset-pills}
## Functions
```{r message=FALSE, warning=FALSE}
# --- Import Packages ---
# import packages
library(knitr)
library(crayon)
library(scales)
library(ggplot2)
library(data.table)
library(tidyverse)
source('global_ndfa_funcs.R')

# --- Import Data from SharePoint ---
get_abs_path <- function(fp_rel){
  # define absolute filepath
  fp_abs <- normalizePath(file.path(Sys.getenv('USERPROFILE'), fp_rel))
  
  return(fp_abs)
}

# --- Add Full Analyte Names ---
add_analyte_names <- function(df){
  # add AnalyteFull column
  df <- df %>%
    mutate(
      AnalyteFull =
        case_when(
          Analyte == 'DisAmmonia' ~ 'Dissolved Ammonia',
          Analyte == 'DisCalcium' ~ 'Dissolved Calcium',
          Analyte == 'DisChloride' ~ 'Dissolved Chloride',
          Analyte == 'Chla' ~ 'Chlorophyll a',
          Analyte == 'DisNitrateNitrite' ~ 'Dissolved Nitrate Nitrite',
          Analyte == 'DOC' ~ 'Dissolved Organic Carbon',
          Analyte == 'TOC' ~ 'Total Organic Carbon',
          Analyte == 'DON' ~ 'Dissolved Organic Nitrogen',
          Analyte == 'DOP' ~ 'Dissolved Organic Phosphate',
          Analyte == 'Pheo' ~ 'Pheophytin',
          Analyte == 'TOP' ~ 'Total Organic Phosphate',
          Analyte == 'DisSilica' ~ 'Dissolved Silica',
          Analyte == 'TSS' ~ 'Total Suspended Solids',
          Analyte == 'VSS' ~ 'Volatile Suspended Solids',
          Analyte == 'TDS' ~ 'Total Dissolved Solids',
          Analyte == 'TKN' ~ 'Total Kjeldahl Nitrogen'
        )
    )
  return(df)
}

# --- Add Phase Actions ---
# adapted from Cat Pien's code
add_phase_actions <- function(df_wq, df_dates){
  # change 'Year' column to character
  df_dates$Year <- as.character(df_dates$Year)

  # combine the two dfs
  df_combined <- inner_join(df_wq, df_dates, by  = 'Year')

  # convert date columns to date type
  cols_date <- c('Date','PreFlowStart','PreFlowEnd','PostFlowStart','PostFlowEnd')

  df_combined[cols_date] <- lapply(df_combined[cols_date], as.Date, format = '%m/%d/%Y')

  # add ActionPhase column and remove non-NDFA data
  df_combined <- df_combined %>%
    mutate(
      ActionPhase =
        case_when(
          Date >= PreFlowStart & Date <= PreFlowEnd ~ 'Pre',
          Date >= PreFlowEnd & Date <= PostFlowStart ~ 'During',
          Date >= PostFlowStart & Date <= PostFlowEnd ~ 'Post'
        )
    ) %>%
    filter(!is.na(ActionPhase))

  return(df_combined)
}

# --- Create df for RL Segments ---
create_seg_df <- function(df){
  # subset out the ND data into own df (based on NA values in 'values' column)
  df_subset <- subset(df, is.na(df$Result))

  # check if any non-detect data
  any_data <- 'Non-detect' %in% df_subset$LabDetect
  if (any_data){
    # create new df for the vertical and horizontal segments
    df_seg <- data.frame(
      x_vert = df_subset$Date,
      xend_vert = df_subset$Date,
      y_vert = 0,
      yend_vert = df_subset$RL,
      x_horz = df_subset$Date-1.7, # 1.7 is arbitrary, change this to change the length of the line
      xend_horz = df_subset$Date+1.7,
      y_horz = df_subset$RL,
      yend_horz = df_subset$RL,
      StationCode = df_subset$StationCode,
      BroadRegion = df_subset$BroadRegion,
      Year = df_subset$Year
    )
    return(df_seg)
  }
  else{
    return(df_subset)
  }
}

# --- Blank Theme for Timeseries Graphs ---
blank_theme <- function(){
  theme_bw() +
    theme(
      panel.grid.major.y = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor = element_blank(),
      axis.text = element_text(color = 'black', size = 10, family = 'sans'),
      axis.text.x = element_text(angle = 45, vjust=0.5, margin = margin(t = 1)),
      strip.text = element_text(size = 11),
      axis.title = element_text(size = 15, face = 'bold'),
      plot.title = element_text(size = 17, hjust = 0.5, face = 'bold'),
      legend.position = 'top',
      legend.title = element_blank(),
      legend.box.margin = margin(-10,0,-10,0),
      legend.text = element_text(size = 9)
    )
}

# --- Create Facet Scatterplots  ---
create_facet <- function(df){
  # import blank theme
  blank_theme <- blank_theme()
  
  # filter df by analyte and region, add action start/end
  df_filt <-
    df_wq %>%
    filter(
      AnalyteFull == analyte,
      BroadRegion == broadregion
    ) %>%
    group_by(Year) %>%
    mutate(
      action_max = unique(PostFlowStart),
      action_min = unique(PreFlowEnd)
    ) %>%
    ungroup()
  
  df_filt <- subset(df_filt, Year %in% c('2011','2012'))#,'2013','2014','2017'))
  df_filt <- subset(df_filt, Result < 300)

  # if (unique(df_filt$AnalyteFull) == 'Chlorophyll a' | unique(df_filt$AnalyteFull) == 'Pheophytin') {
  #     extra_11 <- df_filt[df_filt$StationCode == 'STTD' & df_filt$Year == '2011',][1,]
  #     extra_12 <- df_filt[df_filt$StationCode == 'STTD' & df_filt$Year == '2012',][1,]
  #     extra_11$StationCode <- 'LIB'
  #     extra_12$StationCode <- 'LIB'
  #     df_test <- rbind(df_filt, extra_11, extra_12)
  # }
  
  # create segment (RL) df
  df_seg <- create_seg_df(df_filt)
  
  # define flow action duration
  action_max <- unique(df_filt$PostFlowStart)
  action_min <- unique(df_filt$PreFlowEnd)
  
  
  # check if any/RL data exists
  any_dat <- nrow(df_filt) > 0
  rl_dat <- nrow(df_seg) > 0
  
  # define relevant values
  analyte_unit <- unique(df_filt$Units[df_filt$AnalyteFull == analyte])
  cmap_colors <- c('#999999', '#f781bf', '#B79F00', '#984ea3', '#377eb8', '#e41a1c')
  
  # plot timeseries
  if (any_dat) {
    
    # set limits by region
    buffer <- 0.01
    
    df_filt <- data.table(df_filt)
    
    df_filt <- df_filt[,y_min := min(Result, na.rm = TRUE) - buffer, by = BroadRegion]
    df_filt <- df_filt[,y_max := max(Result, na.rm = TRUE) + buffer, by = BroadRegion]
    
    df_filt$y_min[df_filt$y_min < 0] <- 0
    
    # make a date df for geom_rect b/c we only want one val for each year in the df for dumb drawing reasons
    df_date <- df_filt %>%
      group_by(Year) %>%
      summarize(action_min = min(action_min),
                action_max = max(action_max)) %>%
      ungroup()
    
    # create plot
    p <- ggplot() +
      theme_light() + 
      theme(panel.grid.minor = element_blank()) +
      facet_wrap(. ~ Year, scales = 'free', ncol = 1)#  +
      # annotate('rect', xmin = action_min, xmax = action_max, ymin = -Inf, ymax = Inf, alpha = .08)

    # add timeseries data and flow action box
    p <- p +
      geom_rect(
        df_date,
        mapping = aes(xmin = action_min, xmax = action_max, ymin = -Inf, ymax = Inf),
        alpha = 0.15
      ) +
      geom_point( # points
        df_filt,
        mapping = aes(x = Date, y = Result, color = StationCode),
        size = 2.8
      ) +
      geom_line( # line
        df_filt,
        mapping = aes(x = Date, y = Result, color = StationCode),
        size = 0.8
      )# +
      # geom_point(data = df_filt, aes(y = y_max, x = Date, color = NA)) + # same y-axes
      # geom_point(data = df_filt, aes(y = y_min, x = Date, color = NA))
    
    # add RL segments if they exist
    if (rl_dat) {
      p <- p +
        geom_segment( # vertical segment
          data = df_seg,
          mapping = aes(x = x_vert, xend = xend_vert, y = y_vert, yend = yend_vert, color = StationCode),
          size = 0.8
        ) +
        geom_segment( # horizontal segment
          data = df_seg,
          mapping = aes(x = x_horz, xend = xend_horz, y = y_horz, yend = yend_horz, color = StationCode),
          size = .6,
          lineend = 'square'
        )
    }
    
    # fix asthetics
    p <- p +
      # blank_theme + # theme
      theme(
        strip.text = element_text(color = 'black'),
        legend.position = 'top',
        plot.title = element_text(size = 14, hjust = 0.5),
        legend.text=element_text(size = 7)
        ) +
      labs(color = 'Station:', size = 7) +
      guides(fill = guide_legend(nrow = 1),
             color = guide_legend(nrow = 1)) +
      scale_x_date(labels = date_format('%d-%b'), breaks = pretty_breaks(5)) +
      scale_color_viridis_c(option = 'plasma', end = 0.9) +
      scale_color_viridis_d(option = 'plasma', end = 0.9) +
      xlab('Date') +
      ylab(paste0(analyte, ' (',analyte_unit,')')) +
      ggtitle(paste(broadregion,'Region'))
    
    return(p)

  }
}

# --- Create Table ---
add_table <- function(df){
  # filter df by analyte and year
  df_filt <-
    df %>%
    filter(
      Analyte == analyte,
      Year == year
    )
  
  # cleanup df
  df_filt <- subset(df_filt, select = -c(Note, Year, Analyte))
  
  # make table
  table <- kable(df_filt, align = 'c', caption = '<center><strong>Graph Interpretations</strong></center>')
  
  return(table)
}
```

## Data Cleaning
```{r, message=FALSE, warning=FALSE, results='asis', fig.width=8, fig.height=14}
# --- Import Packages ---
# import packages
library(ggplot2)
library(tidyverse)

# source functions
# source('Water_Quality/Discrete_WQ/timeseries_analysis/d-wq_ts_station_plots_funcs.R')

# --- Import Data ---
# define main FASTR filepath (assumes sync'd with Sharepoint)
fp_fastr <- 'California Department of Water Resources/North Delta Flow Action - Documents/'

# define relative filepaths 
fp_rel_wq <- paste0(fp_fastr,'WQ_Subteam/Processed_Data/Discrete/WQ_INPUT_Discrete_Lab_2021-01-25.csv')
fp_rel_hypo <- paste0(fp_fastr,'WQ_Subteam/Processed_Data/Discrete/Discrete_Hypothesis_Table_MR.csv')
fp_rel_dates <- paste0(fp_fastr,'Data Management/FlowDatesDesignations_45days.csv')
fp_rel_regions = paste0(fp_fastr, 'WQ_Subteam/Processed_Data/Discrete/Analysis/NDFA_map.csv')

# define absolute filepaths
fp_abs_wq <- get_abs_path(fp_rel_wq)
fp_abs_hypo <- get_abs_path(fp_rel_hypo)
fp_abs_dates <- get_abs_path(fp_rel_dates)
fp_abs_regions <- get_abs_path(fp_rel_regions)

# read in data
df_wq <- read_csv(fp_abs_wq)
df_hypo <- read_csv(fp_abs_hypo)
df_dates <- read_csv(fp_abs_dates)
df_regions <- read_csv(fp_abs_regions)

# --- Clean Data In Order To Create Timeseries Plots w/ RLs ---
# create date/year columns (character type)
df_wq$Date <- as.Date(format(strptime(df_wq$DateTime, '%Y/%m/%d'),'%Y-%m-%d'))
df_wq$Year <- format(strptime(df_wq$DateTime, '%Y/%m/%d'),'%Y')
df_regions <- df_regions %>% rename(StationCode = Station)

df_wq <- merge(x = df_wq, y = df_regions[, c('StationCode', 'BroadRegion')], by = 'StationCode')

# add full analyte name column
df_wq <- add_analyte_names(df_wq)

# add in phase actions (will also convert 'Date' column to date type)
df_wq <- add_phase_actions(df_wq, df_dates)

# --- Convert NDs to NA --- 
df_wq$Result[df_wq$LabDetect == 'Non-detect'] <- NA
df_wq$LabDetect[df_wq$Result == '< RL'] <- 'Non-detect'
df_wq$LabDetect[df_wq$Result == '< MDL'] <- 'Non-detect'
df_wq$Result <- as.numeric(df_wq$Result)
```

## Graphs
```{r, message=FALSE, warning=FALSE, eval=FALSE, results='asis'}
# --- Prep for Graphs ---
# list of analytes/stations
analytes <- unique(df_wq$AnalyteFull)
years <- sort(unique(df_wq$Year))
broadregions <- unique(df_wq$BroadRegion)

# change station col to factor type and order it
stat_lvls <- c('RMB','RCS','WWT','RD22','DWT','I80','LIS','STTD','BL5','LIB','RYI','RVB','SDI','SHR','SRH','SRV')
df_wq$StationCode <- factor(df_wq$StationCode, levels = stat_lvls)

# --- Create Time Series --
# create plots
for (broadregion in broadregions){
  cat('\n##', broadregion, '{.tabset .tabset-fade .tabset-pills}')
  for (analyte in analytes) { 
    
    # create time series graphs
    p <- create_facet(df_wq)

    # plot
    if (!length(p) == 0) {
      cat('\n###', analyte, '\n')
      plot(p)
      cat('\n')
    }
  }
}
```

```{r, message=FALSE, warning=FALSE, echo=FALSE, results='asis'}
cat('\n# Graphs {.tabset .tabset-fade .tabset-pills}')
```

```{r, message=FALSE, warning=FALSE, results='asis', echo=FALSE, fig.width=5, fig.height=3, fig.align='center'}
# --- Prep for Graphs --- # 4.7, 9
# list of analytes/stations
analytes <- unique(df_wq$AnalyteFull)
years <- sort(unique(df_wq$Year))
broadregions <- unique(df_wq$BroadRegion)

# change station col to factor type and order it
stat_lvls <- c('RMB','RCS','WWT','RD22','DWT','I80','LIS','STTD','BL5','LIB','RYI','RVB','SDI','SHR','SRH','SRV')
df_wq$StationCode <- factor(df_wq$StationCode, levels = stat_lvls)

# --- Create Time Series --
# create plots
for (broadregion in broadregions){
  cat('\n##', broadregion, '{.tabset .tabset-fade .tabset-pills}')
  for (analyte in analytes) {

    # create time series graphs
    p <- create_facet(df_wq)

    # plot
    if (!length(p) == 0) {
      cat('\n###', analyte,'\n\n')
      plot(p)
      cat('\n')

      # add table
     # t <- add_table(df_hypo)
     #  print(t)
     #  cat('\n')
    }
  }
}
```

